### ISSUE TITLE
pLaTeX の \@makefnmark への追随

### ISSUE THREAD

**Issue by aminophen** [texjporg/jsclasses#1]
> 脚注番号前後の和文文字との間にアキが入る問題

pLaTeX 2016/04/17 で変更した脚注番号の定義に jsclasses も追随させるのはいかがでしょう？

具体的には、現状の
~~~~ tex
\renewcommand\@makefnmark{\hbox{}\hbox{%
  \ifydir \@textsuperscript{\normalfont\@thefnmark}%
  \else\hbox{\yoko\@textsuperscript{\normalfont\@thefnmark}}\fi}\hbox{}}
~~~~
より、[[forum:1783]](http://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=1783) で角藤さんにご提案いただいた
~~~~ tex
\renewcommand\@makefnmark{%
  \ifydir \hbox{}\hbox{\@textsuperscript{\normalfont\@thefnmark}}\hbox{}%
  \else\hbox{\yoko\@textsuperscript{\normalfont\@thefnmark}}\fi}
~~~~
のほうが縦書きの場合によいと思っています。

**Comment by kmaed** [comment]
追随というか，できれば削除がよいですかね．削除すると2013以降2015以前の TeX Live でアキが生じてしまいますが，jsclasses を更新できる人が2016以降の TeX Live（相当のもの）を使えないということは考えづらい……というわけでもないのかな？

古いシステムでバイナリは更新できないという状況があるかもしれない，という話が以前あったように思うのですが，そういう場合は e-pTeX ではないので，そもそもこの問題は生じないのですよね．

**Comment by aminophen** [comment]
なるほど、削除ですか。そのほうがスッキリするかもしれません。同意です。

> 古いシステムでバイナリは更新できないという状況があるかもしれない

については、今回の脚注番号前後のアキ「対策」はバイナリでなく pLaTeX kernel マクロの変更なので、jsclasses を更新可能な状況なら pLaTeX も更新できるはず → と考えると無問題ですね。（細かいですが、アキが入るようになった原因は ptexdir/ptex-base.ch の変更なので、「そういう場合は e-pTeX ではないので」は微妙に違う気がします）

**Comment by aminophen** [comment]
pLaTeX カーネルにごく最近までバグがあって platexrelease しないといけない状況だったことを加味すると、何があってもアキが入らないように jsclasses 側を追随させたほうが良いと思いました。よって削除せず追随で aminophen@1e12a9a にコミットしました。
