### ISSUE TITLE
エンジンが不正の場合のエラーメッセージ

### ISSUE THREAD

**Issue by zr-tex8r** [texjporg/jsclasses#11]
jsclases のクラスは pLaTeX と upLaTex の両方をサポートし、クラスオプション `uplatex` の有無によって使用するエンジンを指定します。ここでもし、使用するエンジンを間違えた場合、次のように、初級者によって理解が難しいエラーが発生します。

（誤って uplatex でコンパイルした場合）

```latex
! LaTeX Error: Font family `JY1+mc' unknown.
```

（誤って platex でコンパイルした場合）

```latex
! LaTeX Error: Font family `JY2+mc' unknown.
```

「エンジンを指定させる」という仕様はこのままでよいと考えています。一方で、実際にはエンジンの自動判定は可能なので、指定されたエンジンが正しいかを検査して、不正である場合はもっと親切なエラーメッセージを出したほうがよいと思います。

**Comment by okumuralab** [comment]
これって，どうして自動判定にしなかったんでしたっけ？

**Comment by doraTeX** [comment]
[ZRさんの記事](http://d.hatena.ne.jp/zrbabbler/20131021/1382361511)にあるように

> ### なぜエンジンは自動判別でないのか
> 
> 実のところエンジンを自動判別するのは難しくない。オプションとしてエンジン（pdflatex 等）を指定することを要求する仕様になっているのは、「これが無いと、どのエンジンを用いてコンパイルするのが正しいのかが不明になる」のでそれを防ぐためである。どのエンジンでもコンパイルが通るとしても、組版の結果は完全に一致するわけではなく、どれか一つのエンジンでの出力が「正しい組版結果」であるはずである。従って、敢えて「想定のエンジン」を明示させているのである。ちなみに、本家の JS クラスでエンジンが upTeX の場合に uplatex を指定させているのも同じ設計思想による。

ということだったと思います。

[以前の議論](https://twitter.com/doraTeX/status/470500710144950272)でも出たように，これはttkさん提唱の設計だそうです。

**Comment by okumuralab** [comment]
doraTeXさん，ありがとうございます。その議論すっかり忘れていました。まったく同意です。

**Comment by zr-tex8r** [comment]
作ってみた。

**Comment by aminophen** [comment]
マージしたので閉じます。
