### ISSUE TITLE
\everyparhook での \inhibitglue 発行対象

### ISSUE THREAD

**Issue by doraTeX** [texjporg/jsclasses#12]
現在の jsclasses では，`\everyparhook` で段落冒頭に `\inhibitglue` を発行する対象となる文字が 

* 「
*  （
*  『
*  ［

の4つとなっています。

しかし，JIS X 0208 の範囲に限っても，始め括弧類としては他に

* 〔
* 《
* ｛
* 【
* 〈

といったものがあります。

こういったものも `\@@inhibitglue` でのチェック対象に増やしてはいかがでしょうか。

JIS X 0213 まで広げれば，さらに

* ｟
* 〖
* 〘

といった開き括弧類もあります。uplatex オプション使用時にはチェック対象をさらに広げるとよいかもしれません。

※ ファイルを  ISO-2022-JP に変換することを考えて〖 などを直接打たないようにするとなると，`\futurelet` における `\ifx` での判定が若干大変かもしれません。（`\kansuji` トリックあたりが必要？）

**Comment by okumuralab** [comment]
そうなんです。開き括弧類については当初は単に実験的に入れたコードがそのままになっています。実装もベタすぎるので，ぜひお願いいたしますm(__)m

文字コードについては，\if西暦 でわからなくなって諦めてしまいました。

**Comment by zr-tex8r** [comment]
ひょっとしたら、「開き括弧である」ことを確かめなくても、
先頭が和文文字であれば `\inhibitglue` する
でも構わないかもしれません。

ただしこの場合は「・」（中黒）の左側グルー（四分）も消えることになりますが。

**Comment by okumuralab** [comment]
なるほど。逆に「・」でなければ…と判断する？

**Comment by zr-tex8r** [comment]
‘\inhibitxspcode`が 2 のものに限定する、という手が考えられますね。

**Comment by okumuralab** [comment]
賢い！
