### ISSUE TITLE
JS クラス成果物のパッケージへの転用

### ISSUE THREAD

**Issue by aminophen** [texjporg/jsclasses#13]
「TODO は Issue に」というわけで：JS クラスが大きすぎる気がするので、前に書き溜めておいたことを含めて置いておきます。
### minijs を upLaTeX でも使えるように

「minijs.sty を upLaTeX で使ってみたらエラーが出た」という話をなんどか twitter でみたことがあります。（今ググったら 2ch のスレでの[コメント](http://toro.2ch.net/test/read.cgi/unix/1380736314/290)が出てきました）

minijs.sty には 3 つのセクションがあって
- min や goth を jis や jisg に変更
- `\@setfontsize` の再定義
- 欧文のサンセリフと和文のゴシックの連動

upLaTeX では JIS メトリックを最初から使っているので最初のセクションは不要（というか、この事実をまったく周知できていないことに問題がある！）ですが、後半は ujarticle / utarticle などで “その場しのぎ” するために有用な内容です。
### pLaTeX のロゴなどをパッケージ化

`\pLaTeX` や `\pTeX` のロゴ、フォントによって最適化した `\LaTeX` など、JS クラス以外でもロゴを使いたいという話。cls から分離して jslogo.sty に書き出し、JS クラスでは後方互換のためデフォルトで読み込む（オプション nojslogo で読み込まないようにもできるとか？）ようにする。

**Comment by zr-tex8r** [comment]
（書こうかな、と思ってたら先を越された。2つとも :smile: ）

**Comment by aminophen** [comment]
お祭りは早い者勝ちです(^ ^)

**Comment by zr-tex8r** [comment]
ロゴについて。

  * `\upTeX`、`\upLaTeX` もほしいよね
  * ファミリが `lmr ` の場合も `cmr` と同じにする
  * txfonts、pxfonts を扱うのなら、その“後継”である newtx、newpx も扱うべきかも

**Comment by okumuralab** [comment]
> お祭りは早い者勝ちです(^ ^)

commitも早い者勝ちですよ！

**Comment by aminophen** [comment]
aminophen/jsclasses で jslogo.dtx を作るところまではやりました。

現状だと、`\上小` という命令があるというだけの理由で `\NeedsTeXFormat{pLaTeX2e}` になっていますが、勿体ない気もしますね。

**Comment by okumuralab** [comment]
\上小 はユーザ定義のマクロとかぶらないようにわざと変な名前にしたのですが，@入りの名前でもよかったですね。外部からは呼ばれないと思うので別の名前でもいいんじゃないかとは思います。

**Comment by aminophen** [comment]
jslogo.sty のなかでは `\@hogehoge` にしておいて（名前は適宜決める）、JS クラスの中には後方互換のため `\def\上小{\@hogehoge}` とでも書いておけば `\NeedsTeXFormat{LaTeX2e}` にできるので、そうしようかと思います。

**Comment by aminophen** [comment]
勢いでほとんど作業してしまいました。aminophen/master@f2edb2f 時点で、既出のうち残っているのは以下のものです：

- JS クラスの新オプション nojslogo で読み込まないようにもできるようにするか？
- ファミリが lmr の場合も cmr と同じにする
- txfonts、pxfonts を扱うのなら、その“後継”である newtx、newpx も扱うべきかも

**Comment by h-kitagawa** [comment]
自分で何もやらず，コメントしているだけなので申し訳ないですが，

 * pTeX のロゴって，どうするのが正式なんでしょう？
  「\TeX の出版への応用 --- 縦組み機能の組み込み ---」(ptex-base/ptexdoc.tex) では次のようになっていますが，せっかくなので，これも欧文ファミリごとに詰め量を変えたらなあ，と思っています．
```tex
\def\pTeX{p\kern-.2em\TeX}
```
   

 * （小声で）エンジン名としての  `\epTeX`, `\eupTeX` もお願いします．

**Comment by kuroky49** [comment]
> pTeX のロゴって，どうするのが正式なんでしょう？
`\LaTeX` の A や E と違って，無理やり詰めるつもりはないのだと思っています．しかし，`\TeX` が一塊になってしまっているので，p と T の間が詰まらないから，その分は詰めましょうということかなと．

なので，全自動でやるなら，アイディアとしては右のようなことをすればよいのだと思います：wd1 = \wd{\hbox{pT}}, wd2 = \wd{\hbox{p\mbox{}T}, \kern{wd1 minus wd2}

**Comment by h-kitagawa** [comment]
> pTeX のロゴ

試してみました．ソースは下，pdf は [ptexlogo.pdf](https://github.com/texjporg/jsclasses/files/364947/ptexlogo.pdf) です．やっぱり，そのまま `pT` と打ったときより詰まっているようです．

```tex
\documentclass{article}
\def\pTlogo{%
  \par\medskip pT\\
  p\TeX\\
  p\kern-.05em\TeX\ (js)\\
  p\kern-.2em\TeX\ (ptexdoc)%
}

\begin{document}
\parindent0pt

\pTlogo
\fontfamily{ptm}\selectfont\pTlogo
\fontfamily{ppl}\selectfont\pTlogo
\end{document}
```

あと，今 grep して調べましたが
```
platex/jsclasses/okumacro.dtx:\newcommand{\pTeXsT}{p\kern-.21em\TeX\kern-.10em s\kern-.21em T}
platex/base/platex.dtx:% \def\pTeX{p\kern-.15em\TeX}
platex/base/platex.dtx:% \def\pLaTeX{p\kern-.05em\LaTeX}
platex/base/platex.dtx:% \def\pLaTeXe{p\kern-.05em\LaTeXe}
platex/base/plnewsc01.tex:\def\pTeX{p\kern-.15em\TeX}
platex/base/plnewsc01.tex:\def\pLaTeX{p\kern-.05em\LaTeX}
```
と，pLaTeX のドキュメントでは `-.15em` のようですね．

**Comment by aminophen** [comment]
> pLaTeX のドキュメントでは -.15em のようですね．

すみません、それは私が入れたような気がします。その元はというと、ptex-base/eptexdoc.tex です。

**Comment by okumuralab** [comment]
ロゴはほんとにむずかしいです。意図はLの最後の上向きのハネがAの両足の真ん中に収まり，Aの上はLやTの高さに一致し，…というふうなことを各フォントで実現するのは，その都度微調整するしかないのかも。
![160715a](https://cloud.githubusercontent.com/assets/3616498/16860549/2a3dc8ba-4a74-11e6-9309-55e17ab05c26.png)

**Comment by aminophen** [comment]
あっ、思い出しました。私が platex.dtx と plnewscXX.tex に入れたロゴの定義は、出典が luatexja.dtx です。これらを加える前（アスキー時代）は、pLaTeX の中のどこにもロゴの定義はありませんでした。アスキー時代のロゴの定義が見えるのは、すでに発見なさっているとおり ptexdoc.tex だけです。

**Comment by aminophen** [comment]
> \TeX が一塊になってしまっているので，p と T の間が詰まらないから，

これはないと思います。\TeX は一塊の「ボックス」ではなく、展開されるので本来のままです。ただ、「一旦ボックスに入れて寸法を測って計算」はアイデアとしてはよいと思います。

ちなみにロゴといえば「\ybaselineshift=10pt とかで A が上がらなくなる」[forum:1851](http://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=1851) というのもあります。これにせよ上記の寸法計算にせよ、うまくやらないと副作用がイロイロ出てしまうので要注意です。

**Comment by yuw** [comment]
> pTeXのロゴ

p-T間をツメるのであれば，ハードコーディングするのが良いと思います．

pTの幅を取得するのはp-Tカーニングが設定されていることを期待してのことと思いますが，p-Tカーニングはあまり設定されないと思います．実際，cmr10.tfm/ec-lmr10.tfmでは特に設定されていないかと思います．

**Comment by kuroky49** [comment]
pTの間にカーニングがなさそうだ，というのは北川さんの作ってくださった例で了解しました．（なので，今朝の提案は無視してください．）

**Comment by zr-tex8r** [comment]
「自然に詰める」のであれば、おそらく T-o カーンの量（cmr10 だと 0.0833em）を採用するのが妥当で、これだと①のようになります。一方、ptexdocの定義（0.15emのカーン）だと②のようになり、「過大に詰めようとしている」ように見えます。

![image-ptex-1](https://cloud.githubusercontent.com/assets/932984/16866936/e3410f9a-4aa9-11e6-8923-91a67ea68d15.png)

**Comment by zr-tex8r** [comment]
自分としては、「どうなるのが良いかの判断基準自体が明確でない」ので、
ptexdoc の定義そのままの固定値でよい、と考えています。

**Comment by okumuralab** [comment]
これは中野賢さんの日本語LaTeX2eブックの冒頭。pとTはカーニングあまりしてないみたい。

![160715b](https://cloud.githubusercontent.com/assets/3616498/16867248/b52d8aa0-4aab-11e6-8267-93f452019f13.png)
