### ISSUE TITLE
twocolumn 指定時に Underfull が起こる

### ISSUE THREAD

**Issue by zr-tex8r** [texjporg/jsclasses#14]
コレをコンパイルすると：

```latex
\documentclass[a4paper,twocolumn]{jsarticle}
\usepackage{lipsum}
\begin{document}
\lipsum[1-3]
\end{document}
```

コレが出てくる：

```
Underfull \vbox (badness 10000) has occurred while \output is active
```

出力結果には影響しないようだけど、とっても気味が悪い。

**Comment by okumuralab** [comment]
これは2段組ではできる限り左右の行（特に最後の行）を揃えるためにこうやっているのですが，何か良いアイデアあるでしょうか。

**Comment by gizakki** [comment]
\normalsizeの行だけを配置したページ（段）でunderfullの警告が現れるのは、\textheightの計算時に「念のため0.1ポイント余分に加えて」いるからだと思います［※注1］［※注2］。この処理を加える必要性はあるのでしょうか。

［※注1：jsclasses.dtx [コミット 910562c での該当箇所](https://github.com/texjporg/jsclasses/blob/910562c88cd7a23ec7336537e6172734d700362e/jsclasses.dtx#L1917)は、` \addtolength{\textheight}{0.1\jsc@mpt}`。］

［※注2：試しに、zr-tex8r さんが示された例のプリアンブルに`\addtolength{\textheight}{-0.1\jsc@mpt}`を追加してコンパイルすると、警告が出力されなくなりました。
（この作業でjsarticle.clsは [コミット 910562c のもの](https://github.com/texjporg/jsclasses/blob/910562c88cd7a23ec7336537e6172734d700362e/jsarticle.cls)を使いましたが、pLaTeXはTeX Live 2015のもの（`pLaTeX2e <2006/11/10> (based on LaTeX2e <2016/03/31> patch level 0)`）です。）］

**Comment by aminophen** [comment]
遅くなりましたが、たしかに gizakki さんのご指摘のように
~~~~ tex
\documentclass[a4paper,twocolumn]{jsarticle}
\usepackage{lipsum}
\makeatletter
\addtolength{\textheight}{-0.1\jsc@mpt}
\makeatother
\begin{document}
{\lipsum[1-3]}
\end{document}
~~~~
とすると警告は出なくなりますね。「念のため0.1ポイント余分に加えて」いるのが「`\baselineskip` の整数倍」にならない場合を想定しているのかなと思って、jsclasses がサポートしているいろいろな a6paper や 21pt など変えて `\textheight` を眺めましたが、結局わからずじまいです。

**Comment by zr-tex8r** [comment]
`\flushbotoom` の状態で、かつカラム内に垂直方向の伸縮が全くない場合は、次のようなことが起こります。

 1. カラムに配置されたものは `\textheight` と僅か（1sp）でもずれると badness 10000 になる。
 2. `\textheight` を僅か（1sp）でも超えることは許されない。

「余裕の 0.1pt」がない場合、この 2 に関して困ったことが起こります。

```latex
\documentclass[a4paper,twocolumn]{jsarticle}
\usepackage{lipsum}
\setlength{\textheight}{634pt}% 余分の0.1ptを消した
\begin{document}
\lipsum[1]\lipsum[3]\par
% ここまでで35行
Line 36.\par
Line 37.\par
\vspace{1sp}
Line 38.\par
Line 39.\par
Line 40.\par
Line 41.\par
\end{document}
```

`\textheight` を「丁度 40 行分」の値（余裕なし）にした場合、40 行が左カラムに入ってアンダーフルが起こりません。これはいいのですが、途中に1spの空きを入れると、40 行目が左カラムに入らなくなって右に移ってしまいます。1spの違いは目には判らないので、左カラムは「下が丸 1 行分空いている」ように見えるわけです。

「行を守るような配置」をするために複雑なマクロを使った場合、計算誤差のため理想的な値より1sp増えてしまう、なんてことは普通に起こり得るでしょう。「0.1ptの余裕」は恐らくこの事態への対策なんだと思います。

**Comment by zr-tex8r** [comment]
今対策として考えているのは、「`\flushbottom` 自体にも余裕を持たせる」ということです。`\flushbottom` の定義内容は

```tex
\let\@textbottom\relax
\let\@texttop\relax
```

ですが、この完全な `\flushbottom` の代わりに次の設定をもちいます。

```tex
\def\@textbottom{\vskip\z@ plus.1\p@}
\let\@texttop\relax
```

もちろん、これでは「下端が 0.1pt の範囲内でずれる」ことになるのですが、よく考えてみると、現状の「完全な `\flushbottom`」を使った場合でも、「伸縮がないので634ptしか入らなかった」カラムと「伸縮があるので634.1ptまできっちり入った」カラムでは 0.1pt ずれているわけです。「0.1ptずれても気ニシナイ」ということなら、上記の設定でも問題はないはずです。

**Comment by okumuralab** [comment]
確かに zr-tex8r さんの改善案のように最初からすべきでした。ただ，今さら「改良」して，微妙なところで既存文書の改ページ位置が変わってしまうとまずいので，消極的です。

**Comment by zr-tex8r** [comment]
うーん、ここを変えて、改ページ位置が変わる可能性があるかというと
「万に一つもない」
とは思いますが、「ゼロ」かというと多分そうじゃないでしょう。

ただ、「だから改修できない」というと、（例の如くの議論で）
例えば「pLaTeXカーネルの xkanjiskip の調整」の影響を受けて改ページ位置が変わる可能性
の方がよほど大きいはずです。

**Comment by okumuralab** [comment]
あと改ページが変わる可能性があるのは1行目にルビや圏点があるときに行がずれるバグの修正もあるので，今まとめてやってしまって，2015→2016で改ページが変わるかもしれませんというアナウンスをすることでしょうか。

**Comment by zr-tex8r** [comment]
jsclasses の中での修正では、 2009-08-26 の `\abovedisplayskip` の修正は、
今回の件よりもずっと大きな影響がありますね。

**Comment by okumuralab** [comment]
はい，歴史的にはいろいろ修正を入れてしまってご迷惑をおかけしています。安全に使っていただくためには，できるだけそういうことを減らしていくべきだと思っています。

**Comment by zr-tex8r** [comment]
よく考えてみると、さっきの `\flushbottom` の話は、出力ルーチンの内部にしか影響しない
（つまり既に改ページ位置が決まった後の話）
ので、これにより改ページ位置が変わる可能性は「ゼロ」でした。

**Comment by okumuralab** [comment]
あれ，そうなのですか？

**Comment by okumuralab** [comment]
あ，見間違えていました。そのとおりですね。ではそうしましょう。

**Comment by zr-tex8r** [comment]
（ひとりごと）

ああ、なるほど。
“他”（LaTeXのカーネル、pLaTeXのカーネル、標準パッケージ、その他の各種パッケージ）が容赦なく変わっている中で、jsclasses **だけ** が「安定」してなければならぬ、というのは（自分には）不合理としか思えないんだが、現実としては（ああ悲しいかな）そうでないと各方面から苦情がくるわけなのか・・・。

やっぱり、フォークした方がいいんじゃないの・・・？

**Comment by okumuralab** [comment]
いや，これについては私の誤解で \def\@textbottom{\vskip\z@ plus.1\p@} の副作用は特になさそうですので問題ないです。すみません。

ただ，例えば \bf を使えなくするとか eqnarray ハックをなくすなどのことでまだ未練を持っておられるようなら，フォークするべきだと思います。

**Comment by aminophen** [comment]
> 例えば \bf を使えなくするとか eqnarray ハックをなくす

繰り返しますが、「使えなくする」とか「ハックをなくす」とは一言も言っていません。「使ってもいいけど編集者の方が非常に困ってますよ」とか「使ってもいいけど別のクラスではハックがないから気をつけてね」とか、少しくらい「警告」なり「ドキュメント化」なりして教えてあげてもいいんじゃないか、というだけです。

それから、jsclasses を変えたら先生に対して「各方面から苦情がくる」のでしょうか。もしそうならば「迷惑をおかけしています」が理解できますが。そこが私の理解の及ばないところです。
