### ISSUE TITLE
互換モードのサポート

### ISSUE THREAD

**Issue by yuw** [texjporg/jsclasses#19]
互換モードのサポートは終了してしまって良いかと思います．

jsclassesを使用するのに2.09を持ち出すことはないかと思います．

**Comment by zr-tex8r** [comment]
えっ、jsclasses って、2.09互換モードをサポートしているの！？

**Comment by yuw** [comment]
`\if@enablejfam`のところに`\if@compatibility`が残っていますね．

**Comment by zr-tex8r** [comment]
一箇所だけある、というのは奇妙で、
まだ、別に互換モードを通すために if文がある、のでもなさそう
（別に if文を外しても互換モードでエラーにならない）です。
たぶん、jarticleあたりからコピーして不注意で残ってしまった、
ということなのでしょう。


しかし、ググった感じだと

```latex
\documentstyle{jsarticle}
```

というオソロシイものを本気で書いている人はいるみたいですね……。
くわばらくわばら……。

**Comment by okumuralab** [comment]
あぁこっちのほうは消し忘れですね

**Comment by abenori** [comment]
消しておきますねー

**Comment by okumuralab** [comment]
> 消しておきますねー

ありがとうございますm(__)m
