### ISSUE TITLE
ページサイズ設定の不具合（graphicx/color の新ドライバ）

### ISSUE THREAD

**Issue by aminophen** [texjporg/jsclasses#2]
[forum:1971](http://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=1971) より。最新の graphics/color ドライバの新機能 (papersize special) が、「jsclasses の 10pt 以外」で間違った用紙サイズを設定してしまう。

~~~~ tex
\documentclass[12pt]{jsarticle}
\usepackage[dvips]{graphicx} % dvips.def [2016/06/17 v3.0m] or later
\begin{document}
あいうえお
\end{document}
~~~~

~~~~ tex
\documentclass[12pt]{jsarticle}
\usepackage[dvipdfmx]{graphicx} % dvipdfmx.def [2016/07/02 v4.10] or later
\begin{document}
あいうえお
\end{document}
~~~~

- jsclasses のオプション `[a4paper,papersize]` を追加しても解決しない。
- graphicx/color の新オプション `[nosetpagesize]` を追加すると解消。

**Comment by aminophen** [comment]
結局 jsclasses ではなく graphics-def 側の問題なので、dvips.def などは LaTeX team 宛て、dvipdfmx.def などは https://github.com/latex3/graphics-def 宛てにレポートするのでしょうか？

**Comment by aminophen** [comment]
とりあえず dvipdfmx.def だけ fork して[改変してみた](https://github.com/aminophen/graphics-def/commit/8c01b584cddd738c68daeb8e4b9c3965de6766f7)のですが、これで dvipdfmx での \mag は解消しますが tombo のときの用紙サイズは正しくなりません。とりあえず上記は pull request したほうがよいでしょうか？（そして、dvips.def のほうはどうしましょうか？）

dvipdfmx.def のコードをみて \stockwidth / \stockheight ってなんだろう、と思ったので、場当たり的に
~~~~ tex
% jsarticle.cls の l.219 付近
\ifpapersize
  \setlength{\@tempdima}{\paperwidth}
  \setlength{\@tempdimb}{\paperheight}
  \iftombow
    \advance \@tempdima 2in
    \advance \@tempdimb 2in
  \fi
% ==== ここから 3 行を追加 ====
  \newdimen\stockwidth \newdimen\stockheight
  \setlength{\stockwidth}{\@tempdima}
  \setlength{\stockheight}{\@tempdimb}
% ==== 追加ここまで ====
  \AtBeginDvi{\special{papersize=\the\@tempdima,\the\@tempdimb}}
\fi
~~~~
すると papersize オプション使用時に用紙サイズが正しくセットされます。\stockwidth / \stockheight はどうやら crop.sty で登場しているのですが、そもそも何のための命令なのでしょう？

**Comment by aminophen** [comment]
> そもそも何のための命令なのでしょう？

memoir のマニュアルをみると、どうやら「用紙サイズの外側のトンボを含めたサイズ」が \stockwidth / \stockheight のようです。ということは、上の対処法がトンボとしては正統と考えてよさそうです(^^;

**Comment by aminophen** [comment]
トンボが大丈夫そうな jsclasses を aminophen@eb2e5f8 で作ってみました。

- dvipdfmx.def は[ここ](https://github.com/aminophen/graphics-def)に置いてあるものを使えば OK です。
- dvips.def は「実際の \mag を基にして補正する計算を行う」をこれから実装すれば多分 OK です。

**Comment by aminophen** [comment]
> graphics-def の \mag 対応

とりあえず pull request 飛ばしました（[latex3/graphics-def#1](https://github.com/latex3/graphics-def/pull/1)）。もし間違ってたら助けてください。

**Comment by zr-tex8r** [comment]
dvips.def / dvipdfmx.def はソレで正しいわけでしょう。

ただし、後できっと geometry を入れてテストしようと考えるでしょうから、
“geometry の変な癖”についても知っておいてください。

  * 例えば `\mag=2000` で `\paperwidth=100pt` (=`200truept`) の場合、geometry は最終的に `\paperwidth=200pt` (=`400truept`) という設定をする。
      * もちろんこれは「`\paperwidth` の値」としてはマチガッテル。
  * `\AtBeginDocument` の中でこのマチガッテル設定を行う。それまでは `\paperwidth=100pt` である。
  * geometry はこのマチガッテル値を利用して papersize special を発行する。
      * “単純”な方法（`papersize=\the\papersize,...`）を用いている。
      * つまり `papersize=200pt,...` となる。だからこれは正しい！
      * 他に“単純”な papersize special を発行している奴がいても大丈夫。←多分コレがマチガッテル設定をする目的だと思う。

従って次のような場合にアレになります。
（これの「dvipdfmx 版」も同様にアレになります。）

```latex
\documentclass[20pt,a4paper]{jsarticle}
\usepackage{geometry}
\usepackage{graphicx}
\begin{document}
Foo\vfill Bar.
\end{document}
```

**Comment by aminophen** [comment]
dvips.def / dvipdfmx.def のかくにんありがとうございます。（これと同じ pull request をまた hyperref にしないといけないような気もしている…）

> “geometry の変な癖”

bxpapersize がナンカいじっているのは確かそこでしたよね。（geometry もアレなのに長年メンテナンス活動が見えないのですが、どうなっているのでしょう？）

**Comment by aminophen** [comment]
で、そもそも geometry は \mag を完全に逆に解釈していて、graphics がどうであれそもそも使い物にならない気がしていたのですが：

~~~~ tex
\documentclass[21pt,a4paper]{jsarticle}
\usepackage[dvipdfm]{geometry}
\begin{document}
あいうえお
\end{document}
~~~~

これの用紙サイズはなんと 435.5 mm x 616.0 mm です。

**Comment by aminophen** [comment]
> pull request

dvipdfmx.def は accept されたようです。そして、dvips.def について David さんから[質問が来ている](https://github.com/latex3/graphics-def/pull/1#issuecomment-231351665)ので、助けていただけると助かります (^^; ちょっとまだ勉強中なもので…

**Comment by aminophen** [comment]
> 従って次のような場合にアレになります。
> （これの「dvipdfmx 版」も同様にアレになります。）

アレにならないように dvipdfmx.def に「geometry.sty が読まれていたら graphicx は何もしない」というパッチを pull request してみました（[latex3/graphics-def#2](https://github.com/latex3/graphics-def/pull/2)）。pdftex.def や xetex.def も変になる場合があるので同様にしてあります。

dvips.def のほうは悩み中です。

**Comment by aminophen** [comment]
graphics-def 側で「\mag が 1000 でない場合は setpagesize を行わない」と改善されたので、用紙サイズが間違われることはなくなりました。よって完了とします。
