### ISSUE TITLE
slide で \subsubsection が罫線に重なる

### ISSUE THREAD

**Issue by aminophen** [texjporg/jsclasses#27]
[forum:1982](http://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=1982) より。
~~~~ tex
\documentclass[slide,papersize]{jsarticle}
\begin{document}
\section{あいうえお}
\subsection{かきくけこ}
\subsubsection{さしすせそ}
\end{document}
~~~~
などで \subsubsection が罫線に重なる。

**Comment by aminophen** [comment]
簡単には以下のようにするとよいようです：
~~~~ tex
\if@twocolumn
  \newcommand{\subsubsection}{\@startsection{subsubsection}{3}{\z@}%
    {\z@}{\z@}%
    {\normalfont\normalsize\headfont}}
\else
  \newcommand{\subsubsection}{\@startsection{subsubsection}{3}{\z@}%
    {\Cvs \@plus.5\Cdp \@minus.2\Cdp}%
    {\if@slide .5\Cvs \@plus.3\Cdp\else\z@\fi}% <= もとは単に {\z@} でした
    {\normalfont\normalsize\headfont}}
\fi
~~~~

**Comment by okumuralab** [comment]
すばらしいです。ありがとうございますm(__)m

**Comment by B-bar** [comment]
ありがとうございます．

**Comment by aminophen** [comment]
> 簡単には以下のようにするとよいようです

別の直し方もできて、それは `\@xsect` の定義を
~~~~ tex
\def\@xsect#1{%
%%%%% 新しい位置（パラメータは微調整）
  \if@slide
    {\vskip.5\jsc@mpt\maybeblue\hrule height0\jsc@mpt depth1\jsc@mpt\vskip.5\jsc@mpt\relax}%
  \fi
%%%%%
  \@tempskipa #1\relax
  \ifdim \@tempskipa<\z@
    \@nobreakfalse
    \global\@noskipsectrue
    \everypar{%
      \if@noskipsec
        \global\@noskipsecfalse
       {\setbox\z@\lastbox}%
        \clubpenalty\@M
        \begingroup \@svsechd \endgroup
        \unskip
        \@tempskipa #1\relax
        \hskip -\@tempskipa
      \else
        \clubpenalty \@clubpenalty
        \everypar{\everyparhook}%
      \fi\everyparhook}%
  \else
    \par \nobreak
    \vskip \@tempskipa
    \@afterheading
  \fi
%%%%% 元のコード
%  \if@slide
%    {\vskip-6\jsc@mpt\maybeblue\hrule height0\jsc@mpt depth1\jsc@mpt\vskip7\jsc@mpt\relax}%
%  \fi
%%%%%
  \par  % 2000-12-18
  \ignorespaces}
~~~~
とすることです（上に書いた `\subsubsection` の定義変更はしない）。これと先ほどの簡単な修正のどちらがよいかはわかりません。

**Comment by B-bar** [comment]
すいません...
その命令文をどのファイルに付け加えたらよいですか？

**Comment by aminophen** [comment]
> 簡単には以下のようにするとよいようです

のものを試したいということであれば、ご自身のソースファイル中に
~~~~ tex
\makeatletter
  \renewcommand{\subsubsection}{\@startsection{subsubsection}{3}{\z@}%
    {\Cvs \@plus.5\Cdp \@minus.2\Cdp}%
    {\if@slide .5\Cvs \@plus.3\Cdp \else \z@ \fi}% <= もとは単に {\z@} でした
    {\normalfont\normalsize\headfont}}
\makeatother
~~~~
と書いてみてください。

**Comment by aminophen** [comment]
> 別の直し方もできて、それは \@xsect の定義を

のものを試す場合は、やはりご自身のソースファイルのプリアンブルに
~~~~ tex
\makeatletter
\def\@xsect#1{%
%%%%% 新しい位置（パラメータは微調整）
  \if@slide
…………… 長いのでここでは省略します ……………
  \par  % 2000-12-18
  \ignorespaces}
\makeatother
~~~~
と書いてみてください。

**Comment by B-bar** [comment]
解決しました！　非常にうれしいです．

**Comment by B-bar** [comment]
解決したと書いてしまいましたが，まだ問題があるようです．
今度は段落題に罫線が重なります．
手間掛けさしてすいません．
[簡単な方.pdf](https://github.com/texjporg/jsclasses/files/379349/default.pdf)
[複雑な方.pdf](https://github.com/texjporg/jsclasses/files/379350/default.pdf)

**Comment by aminophen** [comment]
> 今度は段落題に罫線が重なります

「今度は」というより、前からそうだったと思います。先ほど直したのは \subsubsection だけですので、同じような修正を \paragraph と \subparagraph に入れればよいです。（ちょっと他で手が離せないので、jsarticle.cls の中の当該定義を見つけて私のマネをして \renewcommand してみてください）

「二本線だった」というのは事実誤認であると思います。もともとすべてが一本線だったと思うので。

**Comment by B-bar** [comment]
そうですね．すいません．

**Comment by aminophen** [comment]
（移動中の電車内から投稿；まだ全然 TeX 動かしていませんが、B-bar さんに質問です）

\paragraph とか \subparagraph はたしか、題名の後に改行が入らないと思います。罫線は行の幅いっぱい引かれますから、短い題名では続く文章にも罫線が引かれている状態が予想されます。果たして

- 罫線があったほうがよいと思われますか？
- 罫線が欲しい場合、どのように（長さや位置）引けばよいでしょうか？

（私から単に質問したいだけです。ご意見をお聞かせください）

**Comment by B-bar** [comment]
<p>
私の命令文が悪いのか，\paragraph段落は他と分離しています．
</p>
<pre>
\makeatletter
  \renewcommand{\subsubsection}{\@startsection{subsubsection}{3}{\z@}%
    {\Cvs \@plus.5\Cdp \@minus.2\Cdp}%
    {\if@slide .5\Cvs \@plus.3\Cdp \else \z@ \fi}% <= もとは単に {\z@} でした
    {\normalfont\normalsize\headfont}}
\makeatother

\makeatletter
  \renewcommand{\paragraph}{\@startsection{paragraph}{4}{\z@}%
    {\Cvs \@plus.5\Cdp \@minus.2\Cdp}%
    {\if@slide .5\Cvs \@plus.3\Cdp \else \z@ \fi}% <= もとは単に {\z@} でした
    {\normalfont\normalsize\headfont}}
\makeatother

\makeatletter
  \renewcommand{\subparagraph}{\@startsection{subparagraph}{5}{\z@}%
    {\Cvs \@plus.5\Cdp \@minus.2\Cdp}%
    {\if@slide .5\Cvs \@plus.3\Cdp \else \z@ \fi}% <= もとは単に {\z@} でした
    {\normalfont\normalsize\headfont}}
\makeatother
</pre>
<p>
いづれにせよ罫線は欲しいです．さらに我が儘を言うなら，\paragraphや\subparagraphの罫線はかなり細めかが良いです．位置や長さは他の見出し命令と同じ低層で構わないです．
馬鹿丸出しな投稿すいませんがよろしくお願いします．
</p>

**Comment by aminophen** [comment]
遅くなりましたが、ようやく試しました。長ったらしくみえますが、「簡単な方」の方針を \subsubsection 以外の命令にも全部適用しただけです。ご自分でお試しになる場合は、以下のコードをお使いのソースファイルにコピペしてみてください。（`\documentclass[twocolumn,slide]{jsarticle}` という同時指定の場合にも変なことにならないように弄ってみました）
~~~~ tex
\makeatletter
\if@twocolumn
  \renewcommand{\subsection}{\@startsection{subsection}{2}{\z@}%
    {\z@}{\if@slide .4\Cvs \else \z@ \fi}%
    {\normalfont\normalsize\headfont}}
\else
  \renewcommand{\subsection}{\@startsection{subsection}{2}{\z@}%
    {\Cvs \@plus.5\Cdp \@minus.2\Cdp}% 前アキ
    {.5\Cvs \@plus.3\Cdp}% 後アキ
    {\normalfont\large\headfont}}
\fi
\if@twocolumn
  \renewcommand{\subsubsection}{\@startsection{subsubsection}{3}{\z@}%
    {\z@}{\if@slide .4\Cvs \else \z@ \fi}%
    {\normalfont\normalsize\headfont}}
\else
  \renewcommand{\subsubsection}{\@startsection{subsubsection}{3}{\z@}%
    {\Cvs \@plus.5\Cdp \@minus.2\Cdp}%
    {\if@slide .5\Cvs \@plus.3\Cdp \else \z@ \fi}%
    {\normalfont\normalsize\headfont}}
\fi
\if@twocolumn
  \renewcommand{\paragraph}{\@startsection{paragraph}{4}{\z@}%
    {\z@}{\if@slide .4\Cvs \else -1zw\fi}% 改行せず 1zw のアキ
    {\normalfont\normalsize\headfont ■}}
\else
  \renewcommand{\paragraph}{\@startsection{paragraph}{4}{\z@}%
    {0.5\Cvs \@plus.5\Cdp \@minus.2\Cdp}%
    {\if@slide .5\Cvs \@plus.3\Cdp \else -1zw\fi}% 改行せず 1zw のアキ
    {\normalfont\normalsize\headfont ■}}
\fi
\if@twocolumn
  \renewcommand{\subparagraph}{\@startsection{subparagraph}{5}{\z@}%
    {\z@}{\if@slide .4\Cvs \@plus.3\Cdp \else -1zw\fi}%
    {\normalfont\normalsize\headfont}}
\else
  \renewcommand{\subparagraph}{\@startsection{subparagraph}{5}{\z@}%
    {\z@}{\if@slide .5\Cvs \@plus.3\Cdp \else -1zw\fi}%
    {\normalfont\normalsize\headfont}}
\fi
\makeatother
~~~~

> \paragraphや\subparagraphの罫線はかなり細めかが良いです．位置や長さは他の見出し命令と同じ低層で構わないです．

ただし、現在の jsarticle には罫線の太さを変えるインタフェースが無いので、なにもしていません（もし今後新設するなら、そのやり方をイチから考えて作らなければなりません）。
