### ISSUE TITLE
okumacro と ascmac の衝突

### ISSUE THREAD

**Issue by aminophen** [texjporg/jsclasses#30]
ascmac → okumacro の順で読み込むとエラーになります。これは、okumacro が ascmac 由来のコードを自分で持っている（しかも \newcommand で定義する）からなのですが、「okumacroと衝突するのでascmacパッケージを抜いた．きっとこんな時代遅れのパッケージは使うなという奥村先生のメッセージだらう ^p^」というツイートもあるとおり misleading だと思っています。

okumacro の該当する \newcommand たちを

1. \providecommand に書き換える
2. \expandafter\ifx\csname ver@tascmac.sty\endcsname\relax … \fi に挟む

などして ascmac.sty と衝突しないようにするという対策をとってはどうでしょうか。（仮に対策をとる場合、どちらの方法がよいでしょうか。）

**Comment by okumuralab** [comment]
いやそんなメッセージがあるわけではありません。1でも2でもかまわないと思います。エラーにならなかったものがエラーになる仕様変更は反対ですが，逆ならまったく問題ありません。

もっとも，okumacroは名前からしてもともと私用のマクロで，ひどい作りかけのところとか，あまり他の人に役に立たないところも多いので，最初から書き直して，jsmacroみたいな名前で新たにリリースするという考え方もあると思います。

**Comment by kuroky49** [comment]
TeX Liveには，oberdiek コレクションがあるくらいでして，jsclasses に混ぜて okumacro を配るというのがポリシーとしてはあまりよろしくないように思えます．

最初から書きなおしてとおっしゃっていただいているので，代替物があるものについては，代替物を提示してコードを除去するという手も打ったほうが，管理コストが下がってよいかもしれません．たとえば……
昨日たまたま，http://qiita.com/zr_tex8r/items/42466cbcbeb670a3a2dc を読んだのですが，\ruby も ZR さんのもの（pxrubrica）を理解して使ったほうが，いろいろなことができてよさそうです．

**Comment by aminophen** [comment]
実際 okumacro は「ルビ便利ですよ」と宣伝している Web ページが多くて、それで知っている人も多いですが、一方で ascmac と衝突して困った、という言及をよく見かけます。

pLaTeX は ptex-texmf から全部バラバラの bundle にして Karl さんの ctan2tds に載せてもらえるようになりましたが、jsclasses はまだ角藤さん頼みですね。再構成して自動化に載せる方法を模索するのはよいと思います。
