### ISSUE TITLE
okumacro の \ruby

### ISSUE THREAD

**Issue by aminophen** [texjporg/jsclasses#32]
TODO は　Issue にということで、\ruby の縦書き対応とレジスタ上書きの危険について：

- [okumacroパッケージの\ruby命令は横書きを前提としている。でも適切な設定をすれば縦書きでも使用可能](https://twitter.com/zr_tex8r/status/251009612923428864)、[okumacroの\rubyを縦書きで使う](https://gist.github.com/zr-tex8r/3789322)
- [だとすると、okumacroの\rubyの実装はマズい。#2はユーザ入力なので、\hbox{#2}の実行中に\dimen1が上書きされる可能性があるから。ローカル用レジスタならこんな危険はない。](https://twitter.com/zr_tex8r/status/251181350852370432)

**Comment by aminophen** [comment]
\ruby の縦書き対応は
~~~~ tex
\def\kanjistrut{\iftdir
  \vrule \@height0.5zw \@depth0.5zw \@width\z@
\else
  \vrule \@height0.88zw \@depth0.12zw \@width\z@
\fi}
~~~~
として、レジスタ上書き回避は
~~~~ tex
\newcommand{\ruby}[3][0zw]{%
  \leavevmode
%  \dimen1=#1\relax    %%%%%%% ここから…
  \dimen3=\f@size\p@
  \setbox1=\hbox{#2}%
  \setbox3=\hbox{\rubyfamily\fontsize{0.5\dimen3}{0pt}\selectfont #3}%
  \dimen1=#1\relax     %%%%%%% ここへ！
  \ifdim\dimen1=\z@
    \ifdim\wd1>\wd3 \dimen1=\wd1 \else \dimen1=\wd3 \fi
… 中略 …
      \hbox to \dimen1{\kanjistrut\hfil\unhbox1\hfil}}}\hskip\kanjiskip\relax}
~~~~
にするだけでかなり安全になりますね。いかがでしょうか？

**Comment by doraTeX** [comment]
[和文ゴースト処理によって以下の問題を解決できる](http://doratex.hatenablog.jp/entry/20160613/1465778949)という Issue もありました。

* 後ろに `\kanjiskip` は入るが，前には `\kanjiskip` が入らない。
* 前後に欧文文字が隣接するときに `\xkanjiskip` が入らない。
* 後ろの禁則処理が効かない。

**Comment by aminophen** [comment]
> レジスタ上書き回避

もしかして \dimen3 も同じ危険があるのかもしれない…？

**Comment by aminophen** [comment]
> レジスタ上書き回避：もしかして \dimen3 も同じ危険があるのかもしれない…？

\dimen1 は上記の場所変更で解決しますが、\dimen3 に対策するには \newdimen で名前を付けるしか方法はないですね。\dimen3 は \dimen1 ほど登場しないでしょうし、あまり重要でない気がしてきました。\dimen1 の対処だけでいいかもしれません。

> 和文ゴースト処理によって以下の問題を解決

良さそうなのですが、副作用がないかどうかの確かめかたが判っていません。

**Comment by aminophen** [comment]
#34 で縦組対応とレジスタ上書き回避のコードを送りました（マージありがとうございます＞奥村先生）。ゴーストのほうは doraTeX さんにお任せしようと思います。
