### ISSUE TITLE
jsclasses の \textmc と \textgt

### ISSUE THREAD

**Issue by aminophen** [texjporg/jsclasses#37]
jarticle と jsarticle で比べると、jsarticle だと添字にしたときのサイズが変わりません。これは意図どおりなのでしょうか。
~~~~ tex
\documentclass{jsarticle}% or, jarticle
\usepackage{amsmath}
\begin{document}

\begin{align*}
A_{\textgt{下添字}}, B^{\textmc{上添字}}, \textmc{通常}\textgt{文字}
\end{align*}

\end{document}
~~~~
たしかに、jsclasses の \textmc と \textgt は「和文ではイタリック補正はあまり役に立たず，欧文・和文間のグルーが入らないという副作用もありますので，単純な定義に直します。」と再定義されているのですが、この \xkanjiskip が入らない問題は plfonts.dtx v1.3i (2000/07/13) の時点で修正されています。むしろ、簡略化しすぎてサイズ変更が効かなくなっている、ということのようです。
~~~~ tex
\DeclareRobustCommand\textmc[1]{%
    \relax\ifmmode \expandafter\nfss@text \fi{\mcfamily #1}}
\DeclareRobustCommand\textgt[1]{%
    \relax\ifmmode \expandafter\nfss@text \fi{\gtfamily #1}}
~~~~
とすれば（私の）期待どおりになっています。

**Comment by okumuralab** [comment]
なるほどそうですね。当時の意図はあまり記憶にないのですが，数式中のテキストは日本語も英語もamsmathの\textを使って書くべしというのが自分の流儀ですので，自分では不便ではなかったのでしょう。たぶん互換性の問題はなさそうですので，そう直してくださってかまいません。

**Comment by aminophen** [comment]
\textmc/\textgt と \textrm/\textbf でサイズが違うのが気になっていましたので、直してよいということであれば直します。逆の立場として、「jsclasses を使えば、amsmath を読んでも読まなくても \textmc/\textgt ならサイズが変わらない」という前提を信じている方はいらっしゃるのでしょうか？

**Comment by aminophen** [comment]
master にコミット。
