### ISSUE TITLE
\paragraph の四角

### ISSUE THREAD

**Issue by aminophen** [texjporg/jsclasses#42]
jsclasses は \paragraph で黒四角が出ますが、これは癖があって jclasses より使いづらいという意見をよくみかけます。以前に texqa でも出ていますが、[エディタで開いて消すだけ](https://oku.edu.mie-u.ac.jp/~okumura/texfaq/qa/11576.html)とか、[\renewcommand で再定義すれば良い](https://oku.edu.mie-u.ac.jp/~okumura/texfaq/qa/11578.html)という方法しか出ていません。これはそのとおりなのですが、黒四角がクラスファイルに[直書きされている](http://science3.2ch.net/test/read.cgi/math/1086131126/929)のがそもそもの問題な気もするので
~~~~ tex
\def\paragraphmark{■}
~~~~
のような定義を入れ、\paragraph のほうは \paragraphmark を使うという方法を提案したいです。

**Comment by okumuralab** [comment]
賛成です

**Comment by aminophen** [comment]
お返事ありがとうございます。

\paragraphmark という命令は latex.ltx の中で登場してしまっているので、別の名前を考案する必要があることに気づきました。BXJS のほうは既に同じことを考えて `\jsParagraphMark` という名前を使っているようなので、この名前を流用しようかと思います。
