### ISSUE TITLE
文字コードを UTF-8 に

### ISSUE THREAD

**Issue by aminophen** [texjporg/jsclasses#49]
ptex-ng のような utf8 でないと読めないエンジンをサポートするために、utf8 に変換して

~~~~ tex
\ifx\epTeXinputencoding\undefined\else\epTeXinputencoding utf8\fi
~~~~

を追加するという案についての議論です。

**Comment by aminophen** [comment]
昔の texjporg/ptex-texmf#5 を含めて、今までに出た慎重な意見：

- windows で platex jsclasses.ins とすると自動的に shift_jis encoding で strip されるので問題が起きる。 → Makefile に utf8 必須という意図を書いてあれば問題ない？
- システムを更新できないので古い TeX 環境（2015 年以前）に新しいマクロだけインストールすると問題が起きるかもしれない。 → サポート外とする？

私は GitHub で見やすくなる utf8 に賛成の立場ですが、文字コード絡みで出てくるエラーはわかりにくいので、（たとえ極端な条件であっても）起きうる問題は先に想定しておく必要があると考えています。

**Comment by zr-tex8r** [comment]
とりあえず、自分の感想を書いておきます。

  * 「Makefile に utf8 必須という意図を書いてあれば問題ない？」
      * 普通のLaTeX者（特にWindowsユーザ）はMakefileなんて解らないのでダメ。でも **READMEに書くのなら全く問題ない**。
  * 「古い TeX 環境（2015 年以前）をサポート外にする？」
      * platexに関してはいいかも知れないが、jsclassesについてはダメだと思う。
  * 「`\kansuji`トリックを使ってASCIIにするのは？」
      * jsclassesのクラスをカスタマイズして独自のクラスファイルを作る人は結構いると思うので、TeX言語初級者に解り難いコードは望ましくないと思う。

**Comment by zr-tex8r** [comment]
元ファイル（`*.dtx*）をUTF-8にする方策を考えてみます。

前提：

  * README で `-kanji=utf8` やその他の必要な注意事項を記述する。
  * CTANのファイルはBOM無UTF-8にする。
  * TeXLiveやW32TeXでインストールされるファイルもBOM無UTF=8。
      * e-pTeXが最新版のためこれは問題なし。
  * 自分でパッケージの最新版をインストールするユーザだけが問題。

案：

 1. ファイルが文字コード自動判定でUTF-8に判定されることを確認する。その上で、「文字コードをutf8にする、または、自動判定を有効にする」ことを必須とする。
 2. GitHubにファイルをBOM付UTF-8にする。
 3. GitHubのstrip済ファイルについて、UTF-8版とは別にISO-2022-JP版のファイルを置く。
     * 2/3 の場合、READMEにおいて、GitHubへの適切な誘導を行う。

**Comment by aminophen** [comment]
> - 「Makefile に utf8 必須という意図を書いてあれば問題ない？」
>     - 普通のLaTeX者（特にWindowsユーザ）はMakefileなんて解らないのでダメ。でも **READMEに書くのなら全く問題ない**。

私も同じことを思っていました。Makefile は意思表示のうちに入らないですね。

> - 「古い TeX 環境（2015 年以前）をサポート外にする？」
>     - platexに関してはいいかも知れないが、jsclassesについてはダメだと思う。
> - 「\kansujiトリックを使ってASCIIにするのは？」
>     - jsclassesのクラスをカスタマイズして独自のクラスファイルを作る人は結構いると思うので、TeX言語初級者に解り難いコードは望ましくないと思う。

私はこの2つの観点については考えが欠けていました。

----

ところで、「utf8 にすることによって ptex-ng で使える」というのは本当なのでしょうか。そもそも今まで ptex-ng でテストしたことがなく、「エラーなく動く」ことがサポート内＝「期待どおりの出力になる」かどうかわかっていません。

**Comment by zr-tex8r** [comment]
pTeX-ng は「TeXエンジン部分はupTeXの上位互換」なので、
「ドライバ依存の機能」以外についてはupLaTeXと同じパッケージ・クラスが使えます。

ドライバ依存の部分は少しややこしくて次のようになってます。

  * 基本的にdvipdfmxと同じ。
      * だから `pdf:image` とかのspecialを解釈する。
  * ただし「出力用紙サイズ設定」と「PDFバージョン設定」はpdfTeXと同じ。
      * つまり `\pdfpagewidth` とか `\pdfminorversion` とかが存在する。
      * これに関するspecial（`papersize`とか）はサポートしない。
  * 「出力用紙サイズ設定」がpdfTeXと同じ方式のため、それと密接に関連するmag設定もpdfTeXと同様に動いてほしいのだが、以前に自分が調べたところでは、mag設定時の出力はpdfTeXと同じにならなかった。
      * だからmag設定は事実上使えないと考えるべき。

だから、jsclassesでいうと、次のもの以外は期待通りに動作するはずです。

  * `papersize`
  * `usemag`

もちろん、実際に pTeX-ng でLaTeXを使おうとすると、ドライバ依存のパッケージで色々と苦労することになりそうですが。

**Comment by aminophen** [comment]
> jsclassesでいうと、次のもの以外は期待通りに動作するはずです。
> 
> - papersize
> - usemag

これは 2 つとも jsclasses の主要な特徴だと思います。これらが動かないなら、仮に utf8 にしても jsclasses が ptex-ng をサポートしたとはいえないかもしれません（uplatex カーネルも特に ptex-ng をサポートしたつもりはないようだし）。

そうすると、utf8 にするモチベーションは ptex-ng サポートとは無関係に「GitHub で見やすい」「TeX Live の中の人にやさしい」ということでしょうね。

> 案 1：ファイルが文字コード自動判定でUTF-8に判定されることを確認する。

これは基準が難しいです。特に [forum:2069](http://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=2069) で「バイナリによって自動判定結果が変わる？」ということもあったので怖いです。

> 案 2：GitHubにファイルをBOM付UTF-8にする。

dtx を BOM 付 UTF-8 にするのは簡単ですが、strip すると必ず BOM なしになって出てくるため、毎回 BOM を付けなおす必要があります。Makefile に nkf を仕込めば「BOM を付ける」は自動化できますが、nkf を使う場合は[全角の円記号 U+FFE5 を通すと半角の円記号 U+00A5 に置き換える](https://github.com/texjporg/ptex-texmf/issues/1#issuecomment-173510802)という挙動による事故に気をつけないといけません。

> 案 3：GitHubのstrip済ファイルについて、UTF-8版とは別にISO-2022-JP版のファイルを置く。

branch を切ってファイルを置く、ということになるでしょうか？

**Comment by aminophen** [comment]
そういえば [ptex-texmf#1](https://github.com/texjporg/ptex-texmf/issues/1#issuecomment-173912515) で

> 確かに GitHub から "Download ZIP” をクリックすれば UTF-8 な .cls や .sty が手に入る状況にはなってしまうのですが，エンドユーザは TeX Live 等で入手するので，CTAN の時点で ISO-2022-JP になっていれば問題ないという考え方もできます．

に対して

> ディストリビューションで配るものと開発サイトのものが限りなく近いほうが，フィードバックが得られやすくなると思います．

というのもありました。案 2 は「CTAN やディストリは UTF-8N」、「GitHub は UTF-8 with BOM」という状態だと思いますが、これが「限りなく近い」にあたるかどうかは微妙かもしれません。

**Comment by zr-tex8r** [comment]
>   >   案 1：ファイルが文字コード自動判定でUTF-8に判定されることを確認する。

>   これは基準が難しいです。

了解。


>   >   案 2：GitHubにファイルをBOM付UTF-8にする。

>   dtx を BOM 付 UTF-8 にするのは簡単ですが、strip すると必ず BOM なしになって出てくるため、毎回 BOM を付けなおす必要があります。

なるほど。

UTF-8の有無の違いはユーザも気づき難いので、それをCTANと違うようにするのはマズいかも知れませんね。

>   >   案 3：GitHubのstrip済ファイルについて、UTF-8版とは別にISO-2022-JP版のファイルを置く。

>   branch を切ってファイルを置く、ということになるでしょうか？

jis/ みたいなディレクトリを切って、そこに「strip後のファイル（UTF-8）を（nkfとかで）変換したもの」を置いておく、というイメージでした。CTANのアップロードには含めません。

**Comment by aminophen** [comment]
> jis/ みたいなディレクトリを切って、そこに「strip後のファイル（UTF-8）を（nkfとかで）変換したもの」を置いておく、というイメージでした。CTANのアップロードには含めません。

いまのところ現実的な解決だと私は思いました。もう少し具体化しようとすると、CTAN やディストリに出すファイルは UTF-8 にした上で
`\ifx\epTeXinputencoding\@undefined\else \epTeXinputencoding utf8\fi`
というコードを仕込むのでしょうけど、jis/ 以下にはこのコードを含まず ISO-2022-JP に変換したものを置くのがよいのでしょうか？（手元で試すと ISO-2022-JP エンコードのファイルに \epTeXinputencoding utf8 を書いてあっても（本来なら jis と書くべきところ）、TeX Live 2016 の新しい e-pTeX がちゃんと読めている気がするので、「含まず」にする必要すらない？）

**Comment by aminophen** [comment]
TeX Live 2017 を目処に、この「jsclasses を UTF-8 に」を実現したいと思っています。LaTeX2e も e-TeX 必須になったことですし、躊躇する理由はないとみてよいでしょう。

- TeX Live 2016 以降の e-(u)pTeX では \epTeXinputencoding utf8 が使える
- ptex-ng では e-TeX な upTeX で、\epTeXinputencoding プリミティブが**無い**

この両方をサポートするため、jsclasses の日本語を含むファイル達には

~~~~ tex
\ifx\epTeXinputencoding\@undefined\else \epTeXinputencoding utf8\fi
~~~~

を入れましょう。また、「TeX Live 2015 以前の環境に新しい jsclasses だけダウンロードして使う」という状況も考慮すべきというご意見に従い、「jis/ みたいなディレクトリを切って、そこに strip 後のファイル（UTF-8）を ISO-2022-JP に変換したもの」も置くことにしましょう。

この「ISO-2022-JP への変換」こそ Travis CI のような Linux 仮想環境で iconv を使って自動化するのがよさそうだ、と考えています。

**Comment by aminophen** [comment]
jsclasses と，さらに platex と ptex-base を，近々（今から一ヶ月以内）UTF-8N に変換しようと思います。やりかたはすぐ上のコメントに書いたとおりです。問題が起きそうだったら早めにおしらせください。

**Comment by aminophen** [comment]
utf8 ブランチを作成し，jsclasses を丸ごと UTF-8 に変換してみました。同時に jis/ ディレクトリを作成し，そこに ISO-2022-JP なファイルを置くようにしました。

okumacro の `\−−` みたいな命令が鬼門で，nkf と iconv のどちらを使うかも大事です。さらに，dtx から sty を作る時に platex/uplatex を使うと U+2212 → U+FF0D とか U+2015 → U+2014 とか揺れる可能性があるので，ptexenc を経由せず「そのまま」安全そうな pdflatex を使ってストリップするようにしました。

何かミスしているかもしれないので，テストしてくださると助かります。

**Comment by aminophen** [comment]
なお，まだ各ファイルに

~~~~ tex
\ifx\epTeXinputencoding\undefined\else
  \epTeXinputencoding utf8
\fi
~~~~

を足していないので，後日足します。（これを足せば，TL2016 以降の環境なら全部の OS の pLaTeX / upLaTeX / pLaTeX-ng (ApTeX) の全部で ok になるのですよね？）

**Comment by zr-tex8r** [comment]
チェックしてみましたが、大丈夫のようです。

----

ヤバイ文字一覧：

|X0208文字 |X0221 |CP932 |upTeX |
|:--|:--|:--|:--|
| 01-29 (`0x815C`) | `U+2014` | `U+2015` | `U+2015` |
| 01-33 (`0x8160`) | `U+301C` | `U+FF5E` | `U+301C` |
| 01-34 (`0x8161`) | `U+2016` | `U+2225` | `U+2016` |
| 01-61 (`0x817C`) | `U+2212` | `U+FF0D` | `U+2212` |
| 01-81 (`0x8191`) | `U+00A2` | `U+FFE0` | `U+FFE0` |
| 01-82 (`0x8192`) | `U+00A3` | `U+FFE1` | `U+FFE1` |
| 02-44 (`0x81CA`) | `U+00AC` | `U+FFE2` | `U+FFE2` |

これらのヤバイ文字はupTeXの変換に従う必要があるので、変換後のUTF-8に以下の文字が入ってはいけない。（JISなやつとUTF-8なやつで意味が違ってしまう。）

U+2014, U+FF5E, U+2225, U+FF0D, U+00A2, U+00A3, U+00AC

で、現状のリポジトリの「`/*.{dtx,cls,sty}`」にはダメな文字は入っていない。

**Comment by aminophen** [comment]
確認ありがとうございます。ヤバイ文字がないか確認するスクリプトがあれば今後も便利なんでしょうかね。

上の方で「ptex-base も UTF-8 に変換したい」と書いていたんですが，よく考えたら e- でない pTeX のフォーマット用ファイルとしても使われるのでまずいですね。platex だけ変換するか？は考えます。

**Comment by aminophen** [comment]
1f5f064 で，UTF-8 なファイルに \epTeXinputencoding を足しました。

**Comment by zr-tex8r** [comment]
>   よく考えたら e- でない pTeX のフォーマット用ファイルとしても使われるのでまずいですね。

plainのフォーマットとして使われるファイルは、そもそも非ASCII文字を含んでいないのでは？

**Comment by aminophen** [comment]
> plainのフォーマットとして使われるファイルは、そもそも非ASCII文字を含んでいないのでは

kinsoku.tex がまずいです。

**Comment by aminophen** [comment]
大丈夫になったはずなので jsclasses/utf8 ブランチを master にマージしました。

**Comment by t-tk** [comment]
はるか昔のIssueですが、目についたのでコメントします。

> （手元で試すと ISO-2022-JP エンコードのファイルに \epTeXinputencoding utf8 を書いてあっても（本来なら jis と書くべきところ）、TeX Live 2016 の新しい e-pTeX がちゃんと読めている気がする

アスキー社さんオリジナルの pTeX では
* EUC 指定のときは EUC(8bit), JIS(エスケープ付き7bit)の両方を読み込める
* SJIS 指定のときは SJIS(8bit), JIS(エスケープ付き7bit)の両方を読み込める

となっていたのに習い ptexenc 導入(初期はlibkanjiという名称だった)当初から

* UTF8 指定のときは UTF8(8bit), JIS(エスケープ付き7bit)の両方を読み込める

となっていました。
libkanji以前から「環境非依存のマクロ類はJIS推奨」だった事情から、入出力文字コードガ UTF8 でも JISを読めるようにする期待・要求がありました。
したがって「\epTeXinputencoding utf8 と書いてあるときに JIS が読める」ことを期待して良いと思います。
( 蛇足ながら、ここの Issue の jsclassesの配布をutf8化すること自体には私は賛成です。)

**Comment by t-tk** [comment]
本Issueで未解決の問題は無いように思うので閉じておきます。
もし何かあったら再オープンをお願いします。
