### ISSUE TITLE
jsclasses.dtx 中の作成者・著作権表示

### ISSUE THREAD

**Issue by zr-tex8r** [texjporg/jsclasses#5]
* `\ProvidesPackage` の `okumura` をどうするか。
      * 別に作成者を記す必要がないかも。
  * jsclasses.dtx の冒頭にある著作権表示が LICENSE ファイルの内容と一致していない。

**Comment by okumuralab** [comment]
\author{奥村晴彦} というのもあります。
\author{日本語\TeX 開発コミュニティ} にするかどうか。
LICENSEについては単純にjsclasses.dtxの冒頭を消せばいいんでしょうか。

**Comment by kuroky49** [comment]
黒木の意見は以下です：
- `\ProvidesPackage` は `texjporg` とでもする
- ライセンスは，LaTeX 3プロジェクトとその個人，ASCII Corporation，の部分が少しでも残っているかによって，どうすべきかが変わりそうです．不安なら，jsclasses.dtx 冒頭とLICENSEをマージしたような表記にするのがよいと思います．
- `\author` は，実際中身が開発チームで書き換えられているので，`\author{日本語\TeX 開発コミュニティ}` のほうがふさわしいと思います．

**Comment by abenori** [comment]
> \ProvidesPackage の okumura をどうするか。 別に作成者を記す必要がないかも。

これは前から疑問なんですけど，ここって何を書くんでしょう．jsclasses.dtxの場合は作者の名前になっていますが，殆どの場合パッケージとかの簡単な説明な気がします．（例えばjarticleの場合は「Standard pLaTeX class」）

**Comment by okumuralab** [comment]
okumuraは最初プレースホルダ的に入れて直し損ねているだけだったりします。^^;

**Comment by aminophen** [comment]
> ライセンス表記

pLaTeX や upLaTeX は「BSD 3-Clause」で、pLaTeX の場合は
~~~~
Copyright (c) 2010 ASCII MEDIA WORKS
Copyright (c) 2016 Japanese TeX Development Community
All rights reserved.
~~~~
upLaTeX の場合は
~~~~~
Copyright (c) 2010 ASCII MEDIA WORKS
Copyright (c) 2016 Takuji Tanaka
Copyright (c) 2016 Japanese TeX Development Community
All rights reserved.
~~~~
としたわけなので、jsclasses も似た感じにするのはいかがですか？

> \author

これは `\author{日本語\TeX 開発コミュニティ}` に賛成。

> \ProvidesPackage, \ProvidesClass

これはパッケージやクラスの説明がよいですね。log や \listfiles に出るので、「pLaTeX 用のナントカ」という情報くらいは出たほうがよいと思っていました。

**Comment by zr-tex8r** [comment]
>   ここって何を書くんでしょう．j

先頭は `YYYY/MM/DD` の日付で、この部分は（そもそもオプションを書くなら）必須です。
その後は表示用の任意形式の文字列で、TeX Liveのパッケージを実際に調べた感じだと

  * バージョン番号（`v1.2` とか `r2345` とか）
  * 作成者
  * 簡単な説明

の任意の組み合わせが書かれています。日付しかないものもあります。

**Comment by abenori** [comment]
> okumuraは最初プレースホルダ的に入れて直し損ねているだけだったりします。^^;

なんと！（笑）

> 作成者が書かれているのは少数派ですが、すごく珍しい、というほどではないようです。

調べていただきありがとうございます．もちろん日付より後の話です，すみません．okumuraとかtexjporgとかでも良いのかな？jarticleの真似をするとバージョンとNew pLaTeX classってとこでしょうか．

**Comment by zr-tex8r** [comment]
>   New pLaTeX class

「New」はアレな感じ……。じゃあ「コレは何なのか」といわれたら結局

>  A (u)pLaTeX document class by texjpoorg

みたいな表現しかない気がして、だったらほとんど情報量がない前半を削って

>   by texjporg

でもいいかな、と思ってます。

クラス（.cls）ごとに説明文を変えるべきか（特に jspf とか）も気になります。

**Comment by okumuralab** [comment]
jspfについては，サンプル学会スタイルとして用意したものですが，もうjsclassesといっしょに配布する意味はあまりなくなったので，こっそり削除でもいいかと思います。

**Comment by aminophen** [comment]
`jsclasses (okumura/texjporg)` が簡潔かつ十分だと思いますが、どうでしょう？

**Comment by abenori** [comment]
上の議論に基づいて少しいじってみたものをlicense_testブランチとしてコミットしてみました．

**Comment by okumuralab** [comment]
ちょっとブランチをいじってみました。

**Comment by okumuralab** [comment]
あとiso-2022-jpではやはり見にくいですね。jsclasses.dtxはUTF-8にして，Makefileでiso-2022-jpにしてから変換するというようにしたほうがいいでしょうか。

**Comment by aminophen** [comment]
欲をいえば `texdoc jsclasses` の pdf 中に github の url が出てほしいと思います。

**Comment by okumuralab** [comment]
ですね。テストブランチですからどんどん直接いじっちゃえばどうでしょう？ たいていはうまくマージされるはず。

**Comment by okumuralab** [comment]
> あとiso-2022-jpではやはり見にくいですね。

ひょっとしてdtxはUTF-8でよくて，処理に必要な部分は jis"xxxx で書いちゃうという手も。
でも \if西暦 とかはどうなるのかいまいち理解していません。

**Comment by aminophen** [comment]
github の url をいれてみました。

> ひょっとしてdtxはUTF-8でよくて，処理に必要な部分は jis"xxxx で書いちゃうという手も。

確かに。それでよさそうに思います。`\if西暦` は要調査です。

**Comment by abenori** [comment]
よさそうでしたらマージお願いします．

文字コードについては，\epTeXinputencodingというのもあります．(一応選択肢として．e-pTeX限定となりますが．）

**Comment by okumuralab** [comment]
どなたか頭のはっきりしているかたまーじお願いします（どうやら夏風邪みたい）

**Comment by abenori** [comment]
あれ，お大事になさってください．

ではこっちでやっておきます……と思ったのですが，既にmasterに反映されています？（Gitがわかっていない人）

**Comment by aminophen** [comment]
> 既にmasterに反映されています？

あれ、記憶にないのですが、私が #13 のために fork したときに間違って自分のところと texjporg/master の両方に送ってしまったかもしれないです。もしそうだったらすみません。

**Comment by abenori** [comment]
んじゃぁ既にmasterに入っているということで（笑）ブランチを消せばよいのかな？

**Comment by aminophen** [comment]
消してよいです。すみません、Activity タブ見ると、やっぱり送ったの私みたいですorz（毎日自宅と学校の端末 3 台から git pull/push 繰り返してるので、いつかミスりそうだと思ってました…）
