### ISSUE TITLE
jslogoの命令をPDF文字列中で使うと警告が出る

### ISSUE THREAD

**Issue by zr-tex8r** [texjporg/jsclasses#51]
hyperrefを読み込んだ状態で、jslogoの命令をPDF文字列として解釈される箇所で使ったとします。

```latex
% pLaTeX文書
\documentclass[dvipdfmx,a4paper]{jsarticle}
\usepackage{hyperref}
\usepackage{pxjahyper}
\begin{document}
\section{{\pTeX}と{\upTeX}の違い}
uがあるかないか。
\end{document}
```

この文書をコンパイルすると次の警告が発生します。

```
Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                \kern -0.50003pt
(hyperref)                removed on input line 5.
```

ユーザが自分で `\pdfstringdefDisableCommands` を実行して文字列表現を定義すればよいわけですが、jslogoパッケージであらかじめ文字列表現を与えておくと便利かもしれません。

**Comment by zr-tex8r** [comment]
hyperrefを読み込まずにhyperrefのPDF文字列表現を定義するのは、次のようにすれば実現できます。

```latex
% \pdfstringdefPreHook を（なければ）用意する
\providecommand*\pdfstringdefPreHook{}
% 定義を追加する
\g@addto@macro\pdfstringdefPreHook{%
  \def\pTeX{p\TeX}%
  \def\AmS{AMS}%
  \def\SliTeX{Sli\TeX}%
  \def\BibTeX{Bib\TeX}%
}
% hyperref読込時に \pdfstringdefPreHook が定義済なら
% それをそのまま保持する
```

**Comment by aminophen** [comment]
気になってはいましたが、そういう対処がありえるのですね。

ところで `\AmS` は jslogo.sty 単体でみると「未定義」なのですが、amsmath.sty や amstex.sty をみても \providecommand しているだけで衝突エラーの心配はないため

~~~~
\providecommand{\AmS}{{\protect\AmSfont
  A\kern-.1667em\lower.5ex\hbox{M}\kern-.125emS}}
~~~~

を jslogo.sty に追加するというのも提案したいです。

**Comment by zr-tex8r** [comment]
>   よくみると \AmSfont も未定義でこちらは amsmath.sty が \newcommand することになるので、追加すると厄介なのですかね。

対処するのなら、`\AmSfont` を自前の定義（名前も自前のもの）で置き換える、とするのでしょうね。

**Comment by aminophen** [comment]
> hyperrefを読み込まずにhyperrefのPDF文字列表現を定義する

de24ca9 で jslogo.sty に入れてみました。`\AmSfont` の自前定義はしないことにします。

**Comment by aminophen** [comment]
2017-02-24 を CTAN に出しましたので、close します。
