### ISSUE TITLE
jreport 相当のクラスと abstract 環境

### ISSUE THREAD

**Issue by kmaed** [texjporg/jsclasses#52]
[QA: abstract環境がうまくいかない](http://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=2121)からの issue です．以下は論点のまとめ．

jsclasses では jreport に相当するものを使いたい場合は jsbook に report オプションをつければよいということになっています．しかし，実際には report オプションは両面印刷関係のオプション・レイアウトが調整されるだけらしく，jreport 相当と思って使うと混乱する部分があるようです．

元のトピックで問題になったのが abstract 環境です．一般に abstract 環境は文書の冒頭でその文書全体の概要を書くための環境として定義されていることが多いですが，jsbook での abstract 環境は各章の冒頭でその章の概要を書くことが意図されています（KOMA-Script の \setchapterpreamble に相当）．このため，jreport のように abstract 環境を使おうとすると，元トピックのような混乱が生じることになります．

この状況はよくないので改善がなされると嬉しいですが，過去のバージョンとの互換性は保たれる必要があります．現状では

- \chapter の実行前後で abstract 環境の定義を切り替える
- より jreport の仕様に近い report* オプション（仮）を新設する
- abstract 環境にオプション引数を追加して切り替えられるようにする
- 新たに jsreport.cls を作る

という案が出ています．どうするのがよいでしょうか．

また，abstract 環境以外にも jreport との顕著な相違点があるようでしたらここでご指摘いただければと思います．

**Comment by aminophen** [comment]
> 新たに jsreport.cls を作る

に一票です。

> abstract 環境以外にも jreport との顕著な相違点があるようでしたら

顕著かどうかはさておき、違いとして私が知っているのは以下です。

- jreport では \frontmatter, \mainmatter, \backmatter が未定義だが、jsbook-report は定義済み（ただし組版の挙動的には差はない）
- 二段組の \chapter のときの右カラムの始点が jreport はチャプタータイトルより上になるが、jsbook-report は下になって左カラムに揃う

二段組の \chapter はむしろ jreport/jbook が特別なのかもしれませんが、意図が jclasses.dtx に書かれていないのでよくわかりません。classes.dtx のものと `\@chapter` と `\@schapter` を比べると

~~~~ tex
        \if@twocolumn
          \@topnewpage[\@makechapterhead{#2}]%
        \else
          \@makechapterhead{#2}%
          \@afterheading
        \fi}
~~~~

が削除されているのがわかります。`\@schapter のほうは pldoc.pdf をみると

~~~~ tex
⟨*report|book⟩
…
\def\@schapter#1{%
⟨article⟩ \if@twocolumn\@topnewpage[\@makeschapterhead{#1}]\else
\@makeschapterhead{#1}\@afterheading
⟨article⟩ \fi
}
…
⟨/report|book⟩
~~~~

と、docstrip guard の `<article>` が奇妙な場所に現れています。一応再現ソースを：

~~~~ tex
\documentclass[twocolumn]{jreport} % or, jbook
%\documentclass[twocolumn]{report} % or, book
%\documentclass[twocolumn,report]{jsbook} % or, without report
\usepackage{lipsum}
\begin{document}
\chapter*{あああああ}
\lipsum[1-3]
\end{document}
~~~~

**Comment by mzks** [comment]
後継の位置づけとして論理的に考えても,jsreport.clsを新設するのが良いとおもいます。
TeXのユーザーの大部分はTeXの新機能をどんどん使って行こうというよりは先人のコードを何となく修正するのみなので,既存の環境が変更されるということを徹底して避けるのが無難なように思います.
おそらく,\chapterの実行前後で挙動を切り替えるということで困る人は多くはいないのでしょうが,怪しい挙動として混乱の元なのではないでしょうか。
個人的には自分であれこれ調節するよりTeX様の思し召しにしたがってする組版が最も美しくなる様に設計されて然るべきだと考えているので,reportにも新しいクラスが必要だと思います.
ベータ版としてreport*オプションがあってもいいかもしれません。

**Comment by aminophen** [comment]
たたき台として、docstrip の `<book>` のところを `<book|report>` に機械的に置き換えて jsreport.cls を吐かせてみました。既存の .cls たちは何の変化もありません。diff をとっていただくとわかると思いますが、jsbook.cls とほとんど同じコードで、`\if@report` … `\fi` 条件のところを外に出した形になっています。

abstract 環境についてはまだ何も手を入れていません。

**Comment by aminophen** [comment]
書き忘れましたが、jsreport-strip ブランチです。

**Comment by kmaed** [comment]
自分の意見を書いていませんでしたが，私も jsreport.cls を作るのがよいと思っています．過去のことをあまり気にしなくてよくなるのと，jreport の対応関係としても jsreport があった方が現状の jsbook に report オプションをつけるより自然ですので．

jsreport.cls を作る場合，一度リリースしてしまうと仕様を変更しづらくなってしまうので，どういうものにするべきかをちゃんと詰めるべきだと思います．jreport と現状の相違点を直す以外では，例えば今の jsbook にある各章の概要にあたる環境は必要でしょうか？

aminophen さん，色々とありがとうございます．ちょっとまだ追えていないのですが，あとで見てみます．

mzks さんもありがとうございます．私もそう思います．

**Comment by aminophen** [comment]
> jsreport.cls を作る場合，一度リリースしてしまうと仕様を変更しづらくなってしまうので，どういうものにするべきかをちゃんと詰めるべきだと思います．jreport と現状の相違点を直す以外では，例えば今の jsbook にある各章の概要にあたる環境は必要でしょうか？

jreport と現状の相違点についても、「直す」かどうかは検討してよいと思っています。

「jreport では \frontmatter, \mainmatter, \backmatter が未定義だが、jsbook-report は定義済み」については、jsreport でこれらの定義を削除してよいと考えています。

一方「二段組の \chapter のときの右カラムの始点が jreport はチャプタータイトルより上になるが、jsbook-report は下になって左カラムに揃う」は、jbook と jsbook の間でも同じ違いがありますから、jreport と jsreport の間に違いがあっても不自然でないと思っています。

**Comment by aminophen** [comment]
> 例えば今の jsbook にある各章の概要にあたる環境は必要でしょうか？

私は jsbook の abstract を使用したことがなかったのでなんとも言えませんが、jsreport には要らないのではないかと思います。

**Comment by aminophen** [comment]
jsreport-strip branch 7e54e59 で、jsreport.cls の abstract 環境を jsarticle.cls や kiyou.cls と全く同じ定義に変更しました。これで jreport.cls の挙動に近づいたと思います。

なお、notitlepage のときの定義の分岐処理は jreport に比べて jsreport では複雑になっています。

~~~~ tex
\if@titlepage
  \newenvironment{abstract}{…略…}{…略…}
\else
  \newenvironment{abstract}{%
    \if@twocolumn
      \ifx\maketitle\relax
        …
      \else
        …
      \fi
    \else
      …
    \fi}{…}
\fi
~~~~

これは jarticle に比べて jsarticle が複雑になっているのとまったく同じです。

**Comment by aminophen** [comment]
jsreport.cls の追加について、master にマージしてよろしいでしょうか？

**Comment by kmaed** [comment]
遅くなって申し訳ありません．ようやく試してみたところ，少なくとも abstract に関しては特に問題はなさそうです．アブストラクトの最初の段落にインデントが入らないんだなあ，と思いましたが，これは jreport の仕様を踏襲しているんですかね．

**Comment by aminophen** [comment]
> アブストラクトの最初の段落にインデントが入らないんだなあ，と思いましたが，これは jreport の仕様を踏襲しているんですかね．

「最初の段落にインデントが入らない」は jreport の仕様であると同時に \documentclass[titlepage]{jsarticle} の仕様でもあるので、ここから変えることは考えつきませんでした。実際どちらがいいのでしょう？ titlepage な場合はタイトルだけでなくアブストも単独ページに出るわけですが、あまり論文誌でそういう組版を見たことがないのでどちらがいいか判断つきません。

**Comment by kmaed** [comment]
いずれにせよ，互換性のことを考えると変えない方がよいのかな，と思っています．

英語なら最初の段落をインデントしないのはごく普通ですが，日本語だと最初の段落もインデントするものだと思っていたので，ちょっと疑問に感じたのです．ただ，[JLReq](https://www.w3.org/TR/jlreq/ja/#fig2_5_5-ja) を見ると無いわけではないみたいですね．

**Comment by aminophen** [comment]
> JLReq を見ると無いわけではないみたいですね．

JLReq 3.5.1 c ですね。jsclasses としては互換性の観点から変えないほうがよいと私も思います。

**Comment by aminophen** [comment]
ほかの issue もまとめて片付けていきたいので、問題なさそうな jsreport-strip ブランチを master にマージさせていただきます。

**Comment by aminophen** [comment]
2017-02-24 を CTAN に出しましたので、close します。
