### ISSUE TITLE
minipage 環境の \inhibitglue

### ISSUE THREAD

**Issue by aminophen** [texjporg/jsclasses#58]
http://d.hatena.ne.jp/zrbabbler/20120514/1336952639

> この pTeX の「欠点」はよく知られていて、例えば奥村氏の「新ドキュメントクラス（JS クラス）」では当該のグルーが入らないように調整されている。従って、最初に述べたような「揃わない」現象は起こり得ず、段落頭の開き括弧は全角下がりの位置に揃うことになる。ただし、この対策も完全ではなく、例えば minipage 環境では調整が働かないようである。

minipage 環境で \everypar が空になる、というのは、単に「考慮漏れ」なのでしょうか、それとも「対処不能 or フックを入れて回るのを妥協して入れなかった」なのでしょうか。

**Comment by doraTeX** [comment]
簡易的には，jsclassesの

```tex
\AtBeginDocument{\everypar{\everyparhook}}
```

の代わりに


```tex
\RequirePackage[excludeor]{everyhook}
\PushPostHook{par}{\everyparhook}
```

などとする，という手が考えられますが，いかがでしょうか。

[bxjaprnind パッケージ](http://d.hatena.ne.jp/zrbabbler/20120525/1337966128)を使う方がより本格的ですが。

**Comment by okumuralab** [comment]
すみません，この話題，見落としていました。

意図があったわけではなく，最初いいかげんなパッチをあてて，それを引きずっているだけです。

**Comment by doraTeX** [comment]
>（ただし[この問題](https://twitter.com/doratex/status/536470155732058113)がある）

```
\PushPostHook{par}{\inhibitglue}
```

ではなく

```
\PushPostHook{par}{\everyparhook}
```

ならチェックしているので大丈夫なはずですね。

**Comment by aminophen** [comment]
> \PushPostHook{par}{\everyparhook}

見間違えていました、すみません。

jsclasses 側としてはどうしましょうか。everyhook または bxjaprnind を使えれば汎用的ですが、これは依存パッケージが割と多くなってしまうため、jsclasses 標準で読み込むようにするのは慎重に考えた方がよいと思います。個別の対処を追加する方だとどう書けばよいでしょう？

**Comment by doraTeX** [comment]
minipage単独に対して個別対処するのであれば，latex.ltx の定義を改変して，

```tex
\def\@setminipage{%
  \@minipagetrue
  \everypar{\@minipagefalse\everypar{\everyparhook}}%
}
```

のようにする手が考えられますね。

**Comment by aminophen** [comment]
どこで \everypar を空にしているのか見つけていなかったのですが、なるほど `\@setminipage` でしたか。パッケージを増やさないとするとこれが良さそうです。

**Comment by aminophen** [comment]
6ae14e9 で minipage 環境にも \everyparhook を入れておきました。
