### ISSUE TITLE
\ifdraft は必要か？

### ISSUE THREAD

**Issue by aminophen** [texjporg/jsclasses#6]
前から気になっていたのですが
~~~~ tex
\documentclass{jsarticle}
\usepackage{ifdraft}
\begin{document}
テスト
\end{document}
~~~~
がエラーになります。
~~~~
! LaTeX Error: Command \ifdraft already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.56 }
~~~~
わざわざ jsclasses で \newif\ifdraft を発行していますが、あまり役に立つとは思えないので、やめてしまう or 名称変更を提案します。

**Comment by aminophen** [comment]
ちなみに bxjscls は

> JS クラスは \ifdraft という公開名のスイッチを用いているが、これは ifdraft パッケージと衝突するので、代わりに \ifjsDraft の名前を用い、本文開始時に \ifdraft が未定義の場合に限り、\ifjsDraft を \ifdraft にコピーする処理にする。

となっているようです。ltjsclasses は jsclasses の現状と同じです。

**Comment by zr-tex8r** [comment]
（補足的な何か）

ifdraft パッケージを読み込んだだけでエラーになる、ということは、
ifdraft に依存するパッケージはJSクラスでは全く使えない、ということになります。
代表的なのが animate パッケージです。

**Comment by okumuralab** [comment]
ifdraftで何をしようと考えたのかもう忘れました。jclasses同様に変更しちゃいましょう。これは他に影響ないでしょうし。

**Comment by aminophen** [comment]
削除、でよいですか？ aminophen@1a09586

**Comment by okumuralab** [comment]
つまり

```
\DeclareOption{draft}{\setlength\overfullrule{5pt}}
\DeclareOption{final}{\setlength\overfullrule{0pt}}
```

だけでどうでしょう？

**Comment by aminophen** [comment]
pull request #7 でそのようにしました。
