### ISSUE TITLE
[okumacro] 圏点のずれ

### ISSUE THREAD

**Issue by aminophen** [texjporg/jsclasses#60]
[forum:2272](https://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=2272) の話題です。 texjporg/tex-jp-build#25 の pTeX 本体の修正により，okumacro の圏点がずれるようになった現象への対処が必要です。

~~~~ tex
% --- sample.tex ここから ---
\documentclass{jsarticle}
\usepackage{okumacro}

\begin{document}

晴れ\kenten{のち}曇り

\end{document}
~~~~

**Comment by zr-tex8r** [comment]
例の行を次のように変えると、「“・”のメトリックが左右対称なJFM」であれば、新旧両方のpTeXで想定通りの出力になります。

```tex
  \setbox1=\hbox to\z@{\hbox to 1zw{\hss・\hss}\hss}%
```

**Comment by aminophen** [comment]
> 「“・”のメトリックが左右対称なJFM」であれば、新旧両方のpTeXで想定通りの出力になります。

ありがとうございます。 bc75856 で取り込んでみました。

**Comment by doraTeX** [comment]
upLaTeXだとエラーになりました。

```
Undefined control sequence.
\kenten ...ox 1=\hbox to\z@ {\hbox to 1zw{\hss・ 
                                                  \hss }\hss }\ht 1=.63zw
```

`\hss` と `・` の間にスペースが必要ですね。

**Comment by aminophen** [comment]
ん、確かにスペースを足せば ok なのはわかりますが、upLaTeX で当該の現象が起きるのはなぜ…？

**Comment by aminophen** [comment]
あ、ひらがなと同じ Unicode ブロックに属するからか…

**Comment by doraTeX** [comment]
```
\the\kcatcode`・
```
の結果は，pTeXだと18，upTeXだと17になります。
これは，・(U+30FB)がUnicodeの「カタカナ」ブロックに入っており，カタカナの一種扱いをされているからですね。
ここらへんはpTeXとupTeXの非互換な部分で，[このあたりの話](https://oku.edu.mie-u.ac.jp/~okumura/texfaq/qa/54331.html)とも関係してきます。

**Comment by aminophen** [comment]
uplatex 向けにスペースを入れる修正を加え、regenerate してもう一回 CTAN に 2017-10-04-fix2 として出してみました。幸い（？）CTAN に 2017-10-04 が反映される前だったので、「2017-10-04 は無視してくれ」と書いてみましたがどうなるか…
