### ISSUE TITLE
\tableofcontentsのLeaders

### ISSUE THREAD

**Issue by Yasunari15** [texjporg/jsclasses#67]
Japanese TeX Development Communityのみなさま，こんばんは。

jsclassesの目次の各項目後に引かれる，Leadersは
```
\def\@dottedtocline#1#2#3#4#5{\ifnum #1>\c@tocdepth \else
  \vskip \z@ \@plus.2\jsc@mpt
  {\leftskip #2\relax \rightskip \@tocrmarg \parfillskip -\rightskip
    \parindent \2\relax\@afterindenttrue
   \interlinepenalty\@M
   \leavevmode
   \@lnumwidth #3\relax
   \advance\leftskip \@lnumwidth \null\nobreak\hskip -\leftskip
    {#4}\nobreak
    \leaders\hbox{$\m@th \mkern \@dotsep mu\hbox{.}\mkern \@dotsep
       mu$}\hfill \nobreak\hb@xt@\@pnumwidth{%
         \hfil\normalfont \normalcolor #5}\par}\fi}
```
という定義による`\dotfill`のようなものとなっています。個人的には@doraTeXさんが以前[ブログ](http://doratex.hatenablog.jp/entry/20171219/1513609414)で紹介していらした`\cdotsfill`のように文字の高さの真ん中からLeadersが出てきている方が好みです。
```
\newcommand{\cdotsfill}[1][.25zw]
{\leavevmode\cleaders\hb@xt@#1{\hss$\cdot\m@th$\hss}\hfill\kern\z@\ignorespaces}
```
みなさまはどちらが美文書だと思われるでしょうか。

**Comment by okumuralab** [comment]
皮肉ありがとうございます。ランダムに書架から取り出した横組みの本で，大熊肇『文字の組み方』はベースライン，野村安惠『〈電算植字〉本づくり入門』は仮想ボックス中央ですね。jsclassesはjclassesに倣ってベースラインですが，代替案としては `$\cdot$` の並びではなく仮想ボックス中央にするほうがいいと思います。

**Comment by yuw** [comment]
> みなさまはどちらが美文書だと思われるでしょうか。

美文書の定義がないのでどちらというのはよくわかりませんが，私はベースラインにあるのが好きですね．

**Comment by lemniscati** [comment]
- 個人的には，変更があるのなら，選択できるほうが良いです．
- クラスファイルが更新されても，なるべく同じ組み方をしたいと思ったときに（この意味で後方互換性がほしいときに），対応しやすくなるでしょうから．

**Comment by Yasunari15** [comment]
> 個人的には，変更があるのなら，選択できるほうが良いです．

Optionでということですね。賛成ですね。

**Comment by Yasunari15** [comment]
様々な意見があるようですから，全ての方の組版結果へのこだわりを実現するためにも，
```
\newcommand{\Yasunari15}
{\leaders\hbox{$\m@th \mkern \@dotsep mu\hbox{.}\mkern \@dotsep mu$}\hfill}
```
のような新しいCommandを定義した上で，(もちろん`\Yasunari15`というのは仮です)
```
\def\@dottedtocline#1#2#3#4#5{\ifnum #1>\c@tocdepth \else
  \vskip \z@  @\@plus.2\jsc@mpt
  {\leftskip #2\relax \rightskip \@tocrmarg \parfillskip -\rightskip
    \parindent \2\relax\@afterindenttrue
   \interlinepenalty\@M
   \leavevmode
   \@lnumwidth #3\relax
   \advance\leftskip \@lnumwidth \null\nobreak\hskip -\leftskip
    {#4}\nobreak
    \Yasunari15 \nobreak\hb@xt@\@pnumwidth{%
         \hfil\normalfont \normalcolor #5}\par}\fi}
```
としてUsersがいつでも，
```
\renewcommand{\Yasunari15}{\xleaders\hbox{\scsnowman[hat,nose,muffler,snow]}\hfill}
```
のように自由に変更できるようにするというのはどうでしょうか。

みなさんの意見をお聞かせ頂けますか。僕がPackageを作るということでも構いません。

**Comment by aminophen** [comment]
異論がなさそうなので， #68 をマージして #69 のバグ修正ともども CTAN upload しました。
