### ISSUE TITLE
listings パッケージの title オプションで「1zw」が出力される

### ISSUE THREAD

**Issue by aminophen** [texjporg/jsclasses#71]
https://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=1543 の件です。

> listingsパッケージのtitleオプションで任意のタイトルを付けようとすると，
> タイトルの前に「1zw」という文字が勝手に追加されてしまいます。

（件のソースでは jlisting も使われていたが，この問題には関係ないので消した。）

``` tex
\documentclass[a4j,11pt]{jsarticle}
\usepackage{listings}
\lstnewenvironment{FILE}[2]{
\lstset{%
title={#1},%
tabsize=4,%
breaklines=true,%
basicstyle=\ttfamily,%
framesep=3pt,%
frame=single,%
frameround=tttt,%
#2,%
}}{}

\begin{document}

test

\begin{FILE}{abc}{}
adlfkjel
ajldkfje
\end{FILE}

\end{document}
```

結局，これは「jsclasses の `\@makecaption` の再定義を改善すればよさそうだ」という話でしたが，まだ治っていないようです。

**Comment by h-kitagawa** [comment]
LuaTeX-ja の ltjsclasses では 2015 年の時点で ```\@makecaption``` 再定義を取り込み済みでした（「1zw」と余計な文字列が出力されるのではなく，```! Missing number, treated as zero.``` エラーが当時出た）．

**Comment by aminophen** [comment]
ltjsclasses で実績があるということならなおさら大丈夫そうなので d6fa748 で直しました。

これから 2018-12-11 としてリリースします。
