### ISSUE TITLE
LaTeX2e 2020-10-01 で用紙サイズ指定を間違う

### ISSUE THREAD

**Issue by aminophen** [texjporg/jsclasses#72]
https://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=2944#p17334 に書きましたが，

``` tex
\documentclass[dvipdfmx,slide,a4paper,papersize]{jsarticle}
\begin{document}
ここから\hfill ここまで
\end{document}
```

新しい LaTeX2e 2020-10-01 では「jsclasses で 10pt 以外のフォントサイズを使用した場合」に papersize オプションによる用紙サイズ指定が間違うようです。

**Comment by aminophen** [comment]
``` tex
%\RequirePackage[2020/02/02]{platexrelease}
\documentclass[dvipdfmx,a4paper,12pt,papersize]{jsarticle}
\begin{document}
ここから\hfill ここまで
\end{document}
```

このソースを 2020/02/02 と 2020/10/01 の両方で処理して得た DVI を `dviasm -p output.dvi` としてダンプしてみると，DVI における \special 発行位置が 2020/10/01 では一回 push/pop の内側に入り込んでいます。

``` diff
@@ -16,7 +16,9 @@
 fntdef: jis (10pt) at 9.609985pt
 
 [page 1 0 0 0 0 0 0 0 0 0]
-xxx: 'papersize=597.50787pt,845.04684pt'
+push:
+  xxx: 'papersize=497.92018pt,704.2014pt'
+pop:
 down: 586.640854pt
 push:
   down: -559.529572pt
```

**Comment by h20y6m** [comment]
よくわかっていないのですが `\AtBeginDvi` の引数が展開されるタイミングでしょうか？
jsclasses はその場で展開されることを期待している気がしまが、実際はフックが実行される段階で展開されているような気がします。

**Comment by aminophen** [comment]
はい，\AtBeginDvi の引数の展開タイミングが遅くなったようです。試しに f401517 でなおしてみました。

**Comment by aminophen** [comment]
jsclasses 2020-10-05 が TeX Live に取り込まれました。
