### ISSUE TITLE
「文末ピリオド」\@ の定義

### ISSUE THREAD

**Issue by aminophen** [texjporg/jsclasses#8]
（またもや過去に私があれっと思った記録から掘り出し）

jarticle と jsarticle で以下のソースをコンパイルすると、「jsarticle のとき、かつ jsarticle が意図した新用法のとき」に目次の文末ピリオドが後ろとくっつきます。
~~~~ tex
%\RequirePackage[2014/12/31]{platexrelease} % 古い LaTeX をエミュレートしましょう
\documentclass{jsarticle} % または jarticle にしましょう
\begin{document}
\tableofcontents
\section{I watch TV. Then,}   % 何もしない場合（sentence-ending period にならない）
\section{I watch TV.\@ Then,} % jsarticle が意図した使いかた
\section{I watch TV\@. Then,} % 本来の LaTeX 的な使いかた
\end{document}
~~~~

LaTeX の source2e をみると 2015/01/01 で
~~~~
\def\@{\spacefactor\@m}
~~~~
という古い定義を捨てて
~~~~
\def\@{\spacefactor\@m{}}
~~~~
と再定義しています。`texdoc latexchanges` によると、昔の定義は

> The `\@` command expands to `\spacefactor\@m` in auxiliary files, which then ignores following spaces when it is reprocessed.

という理由でやめたのだそうです。jarticle は「何もしていない」のでこの変更の恩恵を享受していますが、jsarticle は本来の用法と異なる再定義

> 欧文といえば，LaTeX の `\def\@{\spacefactor\@m}` という定義（`\@m` は1000）では `I watch TV\@.` と書くと V とピリオドのペアカーニングが効かなくなります。そこで，次のような定義に直し，I watch TV.\@ と書くことにします。
~~~~
\def\@{\spacefactor3000\space}
~~~~

をしているので問題が残ってしまっています。

**Comment by okumuralab** [comment]
orz...

**Comment by aminophen** [comment]
ペアカーニングが効く「新用法」が使えて、かつ auxiliary files でスペースが残るような再定義、ってどうすればよいのでしょう…
~~~~ tex
\def\@{\spacefactor3000{}}
~~~~
例えばこれなんかどうですか？

**Comment by okumuralab** [comment]
ありがとうございます！そうしましょう。

ちなみに，もっとカーニングがわかりやすいフォントで試してみると，「本来のLaTeX」のまずさがわかると思います：

```
\documentclass{jsarticle} % または jarticle にしましょう
\usepackage{mathpazo,helvet}
\def\@{\spacefactor3000{}}
\begin{document}
\tableofcontents
\section{I watch TV. Then,}   % 何もしない場合（sentence-ending period にならない）
I watch TV. Then,
\section{I watch TV.\@ Then,} % jsarticle が意図した使いかた
I watch TV.\@ Then,
\section{I watch TV\@. Then,} % 本来の LaTeX 的な使いかた
I watch TV\@. Then,
\end{document}
```

**Comment by okumuralab** [comment]
3000{}にして，ついでにREADME.mdも少し書き直しましたがこれでいいんでしたっけ。

**Comment by aminophen** [comment]
いま \def\@{\spacefactor3000{}} じゃなくて \def\@{\spacefactor3000\space{}} になっているみたいですけど、それでいいのでしょうか。

**Comment by okumuralab** [comment]
orz...
あかんですね。夏ボケです。どなたかボケてないかたに作業をお任せしますm(__)m

**Comment by aminophen** [comment]
とりあえず `\@` は直したのでよいですが：

jsclasses は「LaTeX のロゴ」とかいろいろ再定義していて、クラスファイルにしてはやりすぎのような気がします。別途 jslogo.sty のようなファイルにしないと変な誤解を与える可能性があると思います。たとえば `\pLaTeX` というロゴは pLaTeX カーネルで定義していないのに jsarticle では使えてしまいます。これをユーザが知らず知らず使っていて、別のクラスファイルに変えたときに「\pLaTeX のロゴが未定義！」となってしまうのはよくないと思います。クラスファイルはあくまでレイアウトだけに徹するのがよいと思うのですが…

**Comment by okumuralab** [comment]
まぁ今からすれば僭越だったかもしれませんが，もう十何年もこの状態なので，「既知のバグ」として温存するのもありかなと思っています。

**Comment by aminophen** [comment]
jslogo.sty という名前を出したのには、JS クラス以外の人でも \pTeX 等のロゴを使いたいという要望は割とあるはずですので、それを JS クラスだけに localize させず外から呼べるようにしてほしい、という思いがありました。あんまりクラスファイルが大きすぎるとコミュニティではメンテできない、という懸念もあります。

**Comment by okumuralab** [comment]
それでしたらjslogo.styをデフォルトでjs*.clsから読み込むのでどうでしょうか。オプションnojslogoで読み込まないようにもできるとかしてもいいかもしれません。

**Comment by aminophen** [comment]
恐らくそういうやり方のほうがよいと思います。ロゴだけではないとも思いますので、tsarticle（仮）を本当に作る話が出る頃にむけた TODO ということで。

**Comment by aminophen** [comment]
TODO は #13 に飛ばしたのでこちらは閉じます。
