### ISSUE TITLE
圏点の高さと \topskip

### ISSUE THREAD

**Issue by aminophen** [texjporg/jsclasses#9]
（TODO はぜんぶ Issue にしておけばいいのではないかと思ったので、いま一気に直すのは無理でしょうがとりあえず起こしておきます。）

圏点の高さと \topskip に関係するもの：

- １行目に圏点があると、ページ全体の行が僅かにさがる ([forum:1933](http://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=1933))
- 同じ高さになってないじゃん……。([twitter:743382139534639104](https://twitter.com/zr_tex8r/status/743382139534639104))
- [\topskip は1.38zw にしてその分を別のところで調整する](https://github.com/texjporg/jsclasses/pull/3#issuecomment-231267885)

**Comment by aminophen** [comment]
圏点やルビで行が下がるのは困るので、aminophen@a953ff5 で、\topskip を 1.38zw にしました。

\topskip の変更は \headheight と \topmargin に波及するようですので、これらは従来の値を保持するようにしたつもりです（\textheight も変わるかな、と思ったのですが、ちょうど相殺するため変わらないように見えます）。レイアウトはほとんど変わらないつもりですが、勘違いしていないかどうか確認お願いします。

**Comment by okumuralab** [comment]
良さそうに見えます（ほぼ多分）。

**Comment by aminophen** [comment]
良さそう、とのことなのでマージしますね。

**Comment by aminophen** [comment]
すみません、\topskip を増やしたのに \textheight を増やし忘れていたため、\topmargin が縮んでしまっていました（[コレ](https://gist.github.com/zr-tex8r/dfa6372ded4b4c36b84f6e8dab080b63)を見てようやく理解しました）。あとで[修正コード](https://gist.github.com/aminophen/f8c1aeb6cadbd78d531552145a91f002)をコミットしておきます。
